### ISSUE TITLE
Testing on various systems

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/SIRF#10]
Test installation and scripts in as many environments as possible:

* [x] Windows 7, 8?, 10 + some Visual Studio versions
* [x] Various Linux versions + some gcc versions
* [x] MacOS
* [x] Various Matlab releases
* [x] Python 2.* and 3.*
* [x] ~~Real data~~

**Comment by KrisThielemans** [comment]
won't do official Real data testing for V0.9

**Comment by bathomas** [comment]
we have tested some matlab versions but not really used
