### ISSUE TITLE
rename asm_* demos

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#100]
I don't think the innocent reader will know what `asm` stands for. To me, they have to be called `using_acquisition_sensitivity_model_*`. Long, I know. But kind of obvious.

**Comment by evgueni-ovtchinnikov** [comment]
using_acquisition_sensitivity_model_from_ECAT8_normalisation.*
would be far too long

what about something like

     acquisition_sensitivity_from_ecat8.*
     acquisition_sensitivity_from_bin_efficiencies.*
     acquisition_sensitivity_from_attenuation.*

after all, all demos demonstrate usage, so 'using' is extra

**Comment by KrisThielemans** [comment]
good idea! Let's remove the 'using' from the other demos then as well.

**Comment by evgueni-ovtchinnikov** [comment]
done
