### ISSUE TITLE
chained normalisation unstable

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF#104]
Chained normalisation misbehaves now (strange output from e.g. asm_sinograms.py, crashes).

Could it be because of OpenMP?

I switched off OpenMP option for STIR in CMake and deleted /openmp compiler flags, but STIR apparently still builds with openmp as I see messages about 7 threads used

**Comment by KrisThielemans** [comment]
yes,  known bug in OPENMP version on STIR/master. The OPENMP branch should fix that...

Once you've configured CMake, it's kind of hard to change compiler flags. I'd recommend throwing your build away and starting from scratch (i.e. build in a different dir)

**Comment by KrisThielemans** [comment]
OPENMP branch is now merged to STIR/master. Please try again.

**Comment by evgueni-ovtchinnikov** [comment]
still unstable

**Comment by KrisThielemans** [comment]
could you please clarify? Everything fine with STIR/master without STIR_OPENMP, but problems with? sigh.

**Comment by evgueni-ovtchinnikov** [comment]
yes

**Comment by KrisThielemans** [comment]
ok. please create an issue on STIR accordingly

**Comment by evgueni-ovtchinnikov** [comment]
this is a STIR issue now, closing on SIRF
