### ISSUE TITLE
changes to reconstruct_from_listmode.*

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#106]
at least the python version has a test to see if it can make coffee, but as it cannot, it gives a confusing error message :-; let's remove it and put it in a test.

I'd also remove ` lm2sino.flag_off('interactive')` as it's the default.

We're using the template for set_up 
```python
am.set_up(template, attn_image)
```
use `acq_data` instead. no need to re-read the template (it's clearer anyway to use the data).

```python
recon.set_input(acq_data)
```
should not be necessary (as it's set in the objective function).

I think we should remove the "complicated" reconstruction stuff here. We do the loop explicitly here, but that's already in another demo. Instead, I'd just call `process` etc and let it do its thing. Add a comment to refer to the other demo showing on how to add display etc.

Can you try to remove all `set_up` except the `recon` one? STIR should call them.

By the way, I wouldn't have 2 demos, one with only attn, the other with attn, norm and randoms. Just put the latter code in the former.

By the way, the copyright message needs to include 2018 on that one.

**Comment by evgueni-ovtchinnikov** [comment]
flag_on('make coffee'), recon.set_input, extra set_up's, update loop - ok to remove

flag_off('interactive') - would rather keep as it demonstrates how to switch off a flag

am.set_up(template, attn_image) does not re-read the template, am only uses the shared pointer to it to create new PETAcquisitionData object in am.forward()

not quite comfortable with putting ecat8 and randoms in attenuation demo, I believe they would be more useful in reconstruction from listmode

what do we do with the attenuation image offset?

**Comment by KrisThielemans** [comment]
'flag_off('interactive'). sure. let's keep it. add a comment what it does (if it isn't there yet)

I know that `am.set_up(template, attn_image)` is ok, but logically it's confusing for the user, and will also create a copy-paste problem. Best to set-up things with the data that will actually be processed.

Agreed not to put ecat8 and randoms in atten demo. But all of them need to be in the recon from listmode demo.

still thinking about the offset...

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans 
to give you time to think about proper attenuation offset fix, applied temporary workaround of converting attenuation into 'bin efficiencies' (see reconstruct_from_listmode.py on devel);
still vulnerable to the chaining problem, but at least is going to work without openmp (and sometimes with it - chaining rarely crashes in python demos)

**Comment by KrisThielemans** [comment]
another good idea. we'll try to fix this before 1.0.0, but let's leave as-is for 1.0.0-rc1

**Comment by evgueni-ovtchinnikov** [comment]
done enough for 1.0.0
