### ISSUE TITLE
SIRF Version numbers in CMakeLists.txt should not be cached

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#107]
caching them would mean that a git pull with a new version number never gets them into your build.

**Comment by paskino** [comment]
Are you referring to these?
https://github.com/CCPPETMR/SIRF/blob/master/CMakeLists.txt#L42

**Comment by paskino** [comment]
would FORCE be sufficient to fix this?

**Comment by KrisThielemans** [comment]
there is zero reason to have these cached. just use `set` without `CACHE` option

**Comment by KrisThielemans** [comment]
yes those are the lines

**Comment by paskino** [comment]
but then it would be 
`set(VERSION_MAJOR   0)` 
and they won't appear in the cmake-gui, if anyone uses it.

**Comment by KrisThielemans** [comment]
it cannot be in the GUI. We determine the version, not the user!
