### ISSUE TITLE
how to handle release candidates in version numbers

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#110]
Any suggestions on what we do in SIRF (and STIR) with the version number for a RC? We follow the major.minor.patch scheme. Would we do 1.0.0-rc1?

This isn't so important for SIRF right now as we don't export the version number, but it is exported in STIR. 

@casperdcl, any ideas?

**Comment by casperdcl** [comment]
yes, `v1.0.0-rc.1` or `-rc1`, as per https://semver.org/

**Comment by casperdcl** [comment]
The relevant bit is https://semver.org/#spec-item-11

**Comment by KrisThielemans** [comment]
anyone happen to know how CMake's version compare will handle this? (In particular the one set by STIR). I know I could read the doc...

**Comment by casperdcl** [comment]
unfortunately cmake AFAIK ignores labels

```cmake
set(LEFT 1.0.0 CACHE STRING "")
set(RIGHT 1.0.0-rc.1 CACHE STRING "")
if(LEFT VERSION_LESS RIGHT)
	message(STATUS "${LEFT} < ${RIGHT}")
endif()
if(LEFT VERSION_EQUAL RIGHT)
	message(STATUS "${LEFT} == ${RIGHT}")
endif()
if(LEFT VERSION_GREATER RIGHT)
	message(STATUS "${LEFT} > ${RIGHT}")
endif()
```
produces:
```sh
cmake .
...
-- 1.0.0 == 1.0.0-rc1
```

Though there are things like:
- https://github.com/toeb/cmakepp/blob/master/cmake/semver/semver_compare.cmake
- https://gitlab.kitware.com/cmake/cmake/issues/16716

**Comment by KrisThielemans** [comment]
ok. I suppose that makes sense. A release candidate is supposed to be complete. Obviously nobody should use it in production. Let's just use that then.

@evgueni-ovtchinnikov,@paskino can you adjust our ReleaseChecklist to mention the versioning strategy?

**Comment by casperdcl** [comment]
there's always `-alpha`, `-beta`, etc. Let me know if you want semver logic (rather than cmake's built-in basic version_compare) in any cmake files.
