### ISSUE TITLE
show_*_array improvements

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#111]
`show_3D_array` has an undocumented `power` option. I'm not so sure why we'd want it (the user can just run power themselves first?). If we need it, it needs to be documented.

Both `show_*array` functions need capability to set min/max of the colour scale.

Possibly add a colourbar option to `show_3D_array` as well, but that might be hard.

**Comment by evgueni-ovtchinnikov** [comment]
documented power
added scaling option to show_2D_array

**Comment by KrisThielemans** [comment]
probably add `'InitialMagnification','fit'`, or allow user to pass this through somehow

**Comment by evgueni-ovtchinnikov** [comment]
done (on devel)
