### ISSUE TITLE
document randoms-estimation method

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#112]

**Comment by evgueni-ovtchinnikov** [comment]
not something I could do for lack of knowledge about randoms estimation

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov I've done this in doxygen. Can you copy to Python and MATLAB?

could you also expand the Python/MATLAB inline help a bit? I think the most important bit
that is missing are the flags.

**Comment by evgueni-ovtchinnikov** [comment]
done on devel
