### ISSUE TITLE
add long term plan in the doc folder

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#117]
This is still [on the onedrive](https://1drv.ms/w/s!Aj8GcHAEH3_8gcN0mlqVm5T9MCPhrw). @evgueni-ovtchinnikov, can you convert this to Markdown and commit it?

**Comment by KrisThielemans** [comment]
will also need updating http://www.ccppetmr.ac.uk/softwareframework.html as it refers to outdated PDFs.

**Comment by evgueni-ovtchinnikov** [comment]
done
