### ISSUE TITLE
Test Updates

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/SIRF#12]
Add automatic testing after installation/update to SIRF installation/update scripts.

**Comment by casperdcl** [comment]
@KrisThielemans RE: your email about coverage, I've just added https://www.codacy.com/app/CCP-PETMR/SIRF/dashboard and https://www.codacy.com/app/CCP-PETMR/SIRF-SuperBuild/dashboard

**Comment by casperdcl** [comment]
This is more about linting that unit testing, but is still pretty useful, even for catching errors (and free).

**Comment by casperdcl** [comment]
@KrisThielemans / @evgueni-ovtchinnikov RE: more emails, I've added a [coverage](https://github.com/CCPPETMR/SIRF/tree/coverage) branch and uploaded the reports to:

- https://codecov.io/gh/CCPPETMR/SIRF/branch/coverage
- https://coveralls.io/github/CCPPETMR/SIRF

This is just for pSTIR for now (haven't done pGadgetron yet) and both sites report 64.66% coverage

**Comment by KrisThielemans** [comment]
great. Any reason why we need both, especially  as both are based on the same report? codecov seems to give the more useful info but I only looked at this briefly.

@evgueni-ovtchinnikov any reason we shouldn't merge this?

Seems that adding tests to Shapes will increase coverage a lot. Then it's more detail.

**Comment by KrisThielemans** [comment]
@casperdcl when do all these reports get refreshed? with every push? I guess https://www.codacy.com/app/CCP-PETMR/SIRF/dashboard looks at master?

**Comment by casperdcl** [comment]
- `codecov` vs `coveralls`
    + can occasionally report differences (see e.g. badges at the top of [`tqdm`](https://github.com/tqdm/tqdm))
    + have different interfaces, which different people may prefer
    + are pretty much equivalent to set up
- automatically updating
    + I haven't added any logic for this yet
    + The reports right now were manually generated
        + I used my `SIRF-Superbuild:docker` branch to build `SIRF:coverage`, and manually ran tests and uploaded results
    + if we do want to automatically update, I guess we need a push to SIRF to trigger travis to pull SuperBuild:master and use it to build travis' currently checked-out SIRF, followed by running tests and uploading results. let me know if that sounds reasonable.

**Comment by evgueni-ovtchinnikov** [comment]
I am sorry but I could not figure out how to run Casper's tests (except loading into python and executing test_main). Will ctest be able to run them?

**Comment by KrisThielemans** [comment]
thanks for all the hard work on this.

I find that supporing both the `nosetest` and `main` function seems to introduce some overhead. I'm not sure what the benefit is. @evgueni-ovtchinnikov what do you think?

**Comment by casperdcl** [comment]
It seems the `main` function was primarily needed for the `--record` functionality in order to save benchmark files for future use. Technically we shouldn't need this unless we envision wanting to change the test*.txt files in future (and even then, manually editing them should be easy).

**Comment by KrisThielemans** [comment]
ah. I think the record facility is useful. Let's leave that for now then.

**Comment by KrisThielemans** [comment]
I think the test to run `nosetests` is unsafe. It might be running the wrong python. @casperdcl, shouldn't we use
```cmake
add_test(NAME PET_TESTS
  COMMAND nosetests --with-coverage --cover-package=pSTIR src/xSTIR/pSTIR/
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
```

Also, I think the name needs to be something like `PET_PYTHON_TESTS`

**Comment by KrisThielemans** [comment]
in fact, how are we sure this is picking up the correct Python libraries? It would need to set `PYTHONPATH` to the source (not the installed files). Even if we did, it needs to pick up the correct shared-libraries as well, e.g. `src/SIRF-build/src/xSTIR/pSTIR/` for `_pystir.so` with `make`, but  e.g. with Visual Studio (and others) those are in config sub-dirs.

I think this can only be done after install (without a lot of effort).

**Comment by casperdcl** [comment]
good point, turns out (looking at the `travis` `cmake` output for #71) we were using `2.7` even when `python: 3.x` was specified (probably due to `language: cpp`)

discussion continied in #60
