### ISSUE TITLE
mSTIR: Opening AcqusitionData bad error for "."

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#125]
When using `mSTIR.AcqusitionData`, the code checks for a `.` in the filename. If there isn't a `.`, a confusing error is thrown.

**Comment by evgueni-ovtchinnikov** [comment]
if there is no '.' the argument is interpreted as a scanner name

what error do you get?

**Comment by rijobro** [comment]
I accidentally entered the filename without an extension and it threw the error below:
```
ERROR: construct_proj_data_info: span 1 is too large for a scanner with 0 rings
Error using mUtilities.check_status (line 29)
???
ERROR: construct_proj_data_info: span 1 is too large for a scanner with 0 rings
 exception thrown at line 482 of /Users/rich/Documents/OneDrive-UCL/Code/SIRF/Source/src/xSTIR/cSTIR/cstir.cpp

Error in mSTIR.AcquisitionData (line 93)
            mUtilities.check_status(self.name, self.handle_);

Error in reconstruction (line 10)
randoms  = mSTIR.AcquisitionData(randoms_file);
```

**Comment by rijobro** [comment]
The error is understandable now that you've said that it would be interpreted as a scanner name. However, it might be confusing for a user that makes a silly error (like me).

**Comment by evgueni-ovtchinnikov** [comment]
ok I will make it throw 'unknown scanner' error (I thought STIR would do it, but apparently not)

better still 'unknown scanner or missing file extension'

**Comment by rijobro** [comment]
I would say that the latter of the two suggestions is better.

**Comment by evgueni-ovtchinnikov** [comment]
done on devel
