### ISSUE TITLE
need to test the interactive scripts

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#127]
we have some extra scripts that are supposed to be run in spyder or so. these need to be tested before the release

**Comment by evgueni-ovtchinnikov** [comment]
after some small corrections (missing brackets in print, missing pet., pUtil->pUtilities), all interactive scripts seemed to work ok, except that in reconstruction.py all objective function values are zeros

**Comment by KrisThielemans** [comment]
this all works for me, so closing
