### ISSUE TITLE
run_all_scripts.m should not be installed

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#132]
I didn't check if the .py script is installed, but it shouldn't either

**Comment by evgueni-ovtchinnikov** [comment]
If it is not installed, it will not be found by run_all.m scripts in PET, MR and MR/Gadgetron.

My idea was to keep duplication to a minimum: run_all.m is just three lines.

An alternative would be to have three copies of a script blending run_all.m and run_all_scripts.m - not that I mind terribly, just a bit too much duplication to my taste.

**Comment by KrisThielemans** [comment]
ok. that makes sense.

possibly change the name, or put some documentation in there to clarify (it might already be there of course!). then close
