### ISSUE TITLE
remove PET reconstruction set_max_segment_num_to_process

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#145]
Although it is convenient, it is also unsafe and confusing. It's easy to make mistakes where the "sensitivity image" is then inconsistent with the actual reconstruction.

**Comment by KrisThielemans** [comment]
removed it from the demo only for now (094b6a560b30112153e9f04ae11138ee17848ace). Let's discuss if we keep it

**Comment by evgueni-ovtchinnikov** [comment]
fixed on devel
