### ISSUE TITLE
Release 1.0.0-rc.3

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#150]
```
VER=1.0.0-rc.3
```

1. SIRF
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update version numbers in [SIRF/CMakeLists.txt](CMakeLists.txt)
 - [x] update version numbers in the [doc/UsersGuide.md](doc/UserGuide.md) etc
 - [x] run all demos
 - [x] run ctest
 - [x] `git push` 
 - [x] check Travis
 - [x] run doxygen, check and send files for uploading
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 
2. SuperBuild
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update `SIRF-Superbuild/version_config.cmake` with new `SIRF_TAG`
 - [x] `git push`
 - [x] check Travis
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

3. Virtual Machine

 - [x] update version number in [VM_version.txt](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/VM_version.txt)
 - [x] update `vb.name` in [vagrant/vagrantfile](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/Vagrantfile)
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] `git push`
 - [x] `vagrant up`
 - [x] Virtualbox Guest Additions
 - [x] run `first_run.sh` script (gnome settings and zero-fill trick)
 - [x] [deselect](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/README.md#notes-about-ubuntu-box-for-version-100) the serial port.
 - [x] export the VM
 - [x] ctest on VM
 - [x] upload to website
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

4. Website
 - [x] update Software page (version info, VM etc)
 - [x] upload doxygen
- [x] update link for doxygen in [Wiki](https://github.com/CCPPETMR/SIRF/wiki/Software-Documentation)
 - [x] add news flash

5. Announce
 - [x] Send email

6. Tag wikis
 - [x] `git clone https://github.com/CCPPETMR/SIRF.wiki.git; cd SIRF.wiki` (or pull)
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 - [x] `git clone https://github.com/CCPPETMR/CCPPETMR_VM.wiki.git; cd CCPPETMR_VM.wiki` (or pull)
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

https://github.com/CCPPETMR/SIRF/issues/new

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov, worth uploading doxygen again? If not, just tick the boxes.

**Comment by evgueni-ovtchinnikov** [comment]
do not think so - unless somebody was adding C++ stuff to SIRF while I was away, so ticked the boxes
