### ISSUE TITLE
doxygen improvements

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#151]
the [main landing page ](https://www.ccppetmr.ac.uk/sites/www.ccppetmr.ac.uk/files/doxygen/SIRF_1.0.0-rc1ReferenceManualhtml/html/pages.html) linked to both on the wiki and the website is incorrect. It should be https://www.ccppetmr.ac.uk/sites/www.ccppetmr.ac.uk/files/doxygen/SIRF_1.0.0-rc1ReferenceManualhtml/html/index.html.Can this be fixed be now?

The Related pages are quite strange with all the readme's etc appearing. I thought we were going to remove these? (you can exclude files from Doxygen parsing). Fixing this will be for 1.1, so please reassign after fixing the above.

**Comment by paskino** [comment]
Done.

**Comment by evgueni-ovtchinnikov** [comment]
with the correct link related pages no longer appear
