### ISSUE TITLE
new PET data

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF#154]
the PET data layout changed, but I cannot get the new one on my laptop - git pull in SIRF and SIRF/data has no effect, and neither has git submodule update

**Comment by casperdcl** [comment]
maybe `git submodule deinit` first, then `git submodule update --init --recursive`?

**Comment by evgueni-ovtchinnikov** [comment]
in the end, what worked was to delete data folder and to do submodule update as you suggested, thanks!
