### ISSUE TITLE
acquisition model setup missing in reconstruct_from_listmode.*

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF#155]
missing acquisition model setup in in reconstruct_from_listmode.* caused error message

PETAttenuationModel: Forward projector not set correctly. Something wrong.

corrected on SIRF master - do not know how to fix v1.0.0-rc.3 accordingly

**Comment by KrisThielemans** [comment]
thanks. pretty weird as I thought I had tested all these. oh well.

no need to adjust 1.0.0.-rc.3 of course. we'll just put in the final version

**Comment by KrisThielemans** [comment]
I just succesfully ran the demos without your fix.

I wonder therefore if your STIR (or SIRF) is/was out-dated. I believe that we made sure that `AcquisitionSensitivityModel::set_up` calls the appropriate things (probably via `stir::BinNormalisation::set_up` which in this case will/should call `stir::BinNormalisationFromAttenuationImage::set_up`.

**Comment by evgueni-ovtchinnikov** [comment]
git fetch fetches nothing both for SIRF and (UCL) STIR, so I must be using the latest versions - how about you?

somebody added this to the constructor of PETAttenuationModel:

	sptr_forw_projector_ = am.projectors_sptr()->get_forward_projector_sptr();
        if (is_null_ptr(sptr_forw_projector_))
          error("PETAttenuationModel: Forward projector not set correctly. Something wrong.");

where am is PETAcquisitionModel. So if am is not set up I get the above error message.

**Comment by KrisThielemans** [comment]
please check on the VM. you can check versions with git log etc

**Comment by evgueni-ovtchinnikov** [comment]
it turned out, git fetch fooled me! git pull updated STIR and now everything works without additional setup
