### ISSUE TITLE
Objective function value wrongly displayed as zero when using STIR with openmp 

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF#157]
if STIR is built with openmp, steepest_ascent demo prints the objective function values as zeros

at the same time, optimization function scipy.optimize.fminbound seems to get correct objective function values: exactly the same values of the argument x and changes in the image after an iteration are computed as without openmp - but objective function values are reported to be 0!

**Comment by KrisThielemans** [comment]
confirmed that this is still the case. This must be a STIR bug.
