### ISSUE TITLE
travis gadgetron tests with DEVEL_BUILD=ON fail

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#158]
End of [log](https://api.travis-ci.org/v3/job/357422034/log.txt) is
```
$ cat gadgetron.log
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
```
this is saying that a `std::string` was initialised with a NULL ptr.

as other configurations are ok this is likely a gadgetron master problem.

**Comment by casperdcl** [comment]
might be worth opening an issue on the gadgetron repo?

**Comment by evgueni-ovtchinnikov** [comment]
I did (#596)

**Comment by casperdcl** [comment]
link: https://github.com/gadgetron/gadgetron/issues/596

**Comment by paskino** [comment]
but some of the builds with `DEVEL_BUILD=ON` did not fail. This [one ](https://travis-ci.org/CCPPETMR/SIRF/jobs/373350465) for instance.

**Comment by xueh2** [comment]
do you have the entire gadgetron.log to share?

**Comment by casperdcl** [comment]
@xueh2 unfortunately as per the original description, the only thing in the `gadgetron.log` is the `std::logic_error`. `gadgetron` throws this error and crashes immediately upon startup.

```bash
$ gadgetron > gadgetron.log
$ cat gadgetron.log
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
```

**Comment by KrisThielemans** [comment]
@xueh2, this might have been a `ccache` problem with our builds. I think it has disappeared now but not sure as we're now having a bug ourselves. Will let you know.

**Comment by casperdcl** [comment]
just completely cleared my `ccache` and rebuilt, still have the same error (using https://github.com/gadgetron/gadgetron/commit/73ab0797db2ca9124c4cd268587d3c76665d0d5d)

**Comment by KrisThielemans** [comment]
yes. also [on Travis](https://api.travis-ci.org/v3/job/374606568/log.txt). @casperdcl, can you specify your OS and environment?

**Comment by KrisThielemans** [comment]
This is due to a missing `GADGETRON_HOME` env variable. Let's see first what upstream says.

**Comment by KrisThielemans** [comment]
closing as will fix with https://github.com/CCPPETMR/SIRF-SuperBuild/issues/115
