### ISSUE TITLE
C++ test failed but not reported by ctest

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#159]
See #156 for a case where the PET_TESTS failed due to the listmode file being moved (v1.0.0-rc.3), but the test claiming it passed anyway.

**Comment by evgueni-ovtchinnikov** [comment]
Are you sure you are using 1.0.0? That bug was fixed in the very last commit to SIRF master before tagging (d4dddd..de156).

**Comment by evgueni-ovtchinnikov** [comment]
changed filename in test4.cpp, ctest failed (on VM and on dettifoss), so closing the issue

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov,  thanks for checking. Could you please confirm you ran this via the SuperBuild?

**Comment by evgueni-ovtchinnikov** [comment]
I run ctest from buildVM folder on VM and from build folder on dettifoss - so I understand that was SuperBuild ctest?

**Comment by KrisThielemans** [comment]
perfect. thanks!
