### ISSUE TITLE
Real Data

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/SIRF#16]
- [ ] (non-TOF) Unlisting of PET data (single time frame)
- [ ] randoms, norm, attenuation, scatter for Siemens mMR
- [ ] norm for GE Signa
- [ ] “native” reading of Siemens PET data (without conversion)
# Ambitious
* [ ] Provide PET and MR phantom data and sample reconstructions

**Comment by KrisThielemans** [comment]
closing this as we have separate issues, i.e. #53,#54, #55, #56
