### ISSUE TITLE
PLSPrior set/get functions

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#162]
The STIR master branch now has set/get functions, e.g. set_alpha, set_anatomical_filename etc. It would be useful for these to be exposed in SIRF. 

However, since these methods don't exist in older versions of STIR, we should wait until the next next tagged version of STIR. That way, we can expose with a preprocessor so that SIRF will still compile with older versions of STIR.

**Comment by KrisThielemans** [comment]
Due to #157 we have to rely on latest STIR, so this could be done now. @evgueni-ovtchinnikov, please assign to feasible milestone (I'm not sure how much effort this is).

**Comment by evgueni-ovtchinnikov** [comment]
exposed in Python set/get methods for only_2D, anatomical and kappa images

can easily do the rest except set_alpha and other private methods of PLSPrior (so probably no point doing get_alpha etc right now)

**Comment by KrisThielemans** [comment]
`stir::PLSPrior` now has the necessary members (since [Oct 2018](https://github.com/UCL/STIR/tree/a5fefe741f97a65de95ac51ac612719f5000ac47)).

@evgueni-ovtchinnikov can you now put this into SIRF? Thanks
