### ISSUE TITLE
examples/Python/MR/Gadgetron/fully_sampled_recon_single_chain.py

### ISSUE THREAD

**Issue by DANAJK** [CCPPETMR/SIRF#167]
1) Incorrectly displays modulus data when labelled as imaginary. Problem is with 'abs' in:
show_3D_array(abs(image_array[1::2,:,:])

2) Appears to reconstruct 3D data, but fails in show_3D_array:
sirfuser@ubuntu-xenial:~/CCP-Elba$ python /home/sirfuser/devel/buildVM/sources/SIRF/examples/Python/MR/Gadgetron/fully_sampled_recon_single_chain.py -f m3d.h5 -o m3d_out.h5 -p .
Input stream has terminated
Traceback (most recent call last):
  File "/home/sirfuser/devel/buildVM/sources/SIRF/examples/Python/MR/Gadgetron/fully_sampled_recon_single_chain.py", line 118, in <module>
    main()
  File "/home/sirfuser/devel/buildVM/sources/SIRF/examples/Python/MR/Gadgetron/fully_sampled_recon_single_chain.py", line 99, in main
    show = False)
  File "/home/sirfuser/devel/install/python/pUtilities.py", line 138, in show_3D_array
    rows = int(round(math.sqrt(n*nx/ny)))
ZeroDivisionError: integer division or modulo by zero

3) When applied to our dataset 'simulated_MR_2D_cartesian.h5', it labels output images as two slices, but I believe they are 2 repetitions of one slice.

**Comment by evgueni-ovtchinnikov** [comment]
1. corrected
2. need your data to debug
3. slice number means its number in the whole set of slices wherever they come from (different z, different repetition etc.) - do not see how to label slices otherwise, too many dimensions:(

**Comment by DANAJK** [comment]
1.  corrected  - Thanks
  2.  need your data to debug  - run siemens_to_ismrmrd on this 3D dataset to generate an input h5 file: https://www.dropbox.com/s/tz7q02fziskq9u7/meas_MID00103_FID57244_test.dat?dl=0
  3.  slice number means its number in the whole set of slices wherever they come from (different z, different repetition etc.) - do not see how to label slices otherwise, too many dimensions:(  . ‘slice’ implies spatial position, suggest subplot title is something like  ‘3rd dimension index’ or ‘ind3’.

**Comment by evgueni-ovtchinnikov** [comment]
2. I do not have siemens_to_ismrmrd - can you not just let me have m3d.h5?
By the way, what makes you think the reconstruction succeeded? Can you print image_data.number() and image_data.norm()? image_array.shape is clearly wrong as show_3D_array found that ny = image_array.shape[1] = 0.

3. So you suggest to have 'slice with 3rd dimension index 1'  or 'slice with ind3 = 1' instead of 'slice 1'? The former is too long and the latter rather cryptic, are they not?
@ckolbPTB: any ideas?
@KrisThielemans: I suggest we have a discussion on this on a Friday tcon, and for the time being shift it to milestone 1.2.

**Comment by evgueni-ovtchinnikov** [comment]
2. the error is due to failure to read the saved image - have no idea why. for now commented out the reading.
3. the point is - how to adjust. i considered David's suggestions and pointed out at their limitations. it will not take more than 5 min to implement any of the two.

**Comment by KrisThielemans** [comment]
how much memory does your VM have? (check in Machine Settings in the VB interface). If you have spare, try to increase it (shutdown VM, change memory, start it).

**Comment by evgueni-ovtchinnikov** [comment]
on laptop i use VM with 4096MB, which leaves me with about 3GB free memory

tried 8192MB VM on desktop, ran 6 times - no crashes, so must be the VM memory issue

btw, implemented empty-chain connection check, now have correct error traceback (to Reconstructor.process) and more useful message, @DANAJK please try again on m3d.h5
