### ISSUE TITLE
SIRF/src/common/Utilities.py

### ISSUE THREAD

**Issue by DANAJK** [CCPPETMR/SIRF#168]
show_3D_array displays in colour. This is not really meaningful in MR for modulus, real or imaginary data (better as gray scale). Phase is OK displayed in colour, but then a colour bar needs to be added in order to read off the values.
Can either the default be changed, or an option flag be added to the input?

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov, is this feasible by 1.1? Related to #111.

**Comment by evgueni-ovtchinnikov** [comment]
grayscale plotting enabled
