### ISSUE TITLE
Other Software features

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/SIRF#17]
* [ ] Basic math manipulations for images and AcquisitionData?
* [x] Sort out some naming eyesores (PoissonLogLh_LinModMean_AcqMod etc.).
* [ ] PET ObjectiveFunction
    * [ ] Image: parameters to estimate
    * [ ] AcquisitionData
    * [ ] AcquisitionModel
    * [ ] Noise model: Poisson/Gaussian etc
    * [ ] Prior

**Comment by KrisThielemans** [comment]
naming fixed now. objective function problems currently resolved by make_Poisson...

**Comment by KrisThielemans** [comment]
Split into #34  and #35
