### ISSUE TITLE
inappropriate 'Close Figure 1 window to continue...'

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#175]
`show_2D_array` (et al?) print this at the end. However, it is only correct for certain matplotlib backends. When run in `ipython` or jupyter notebooks, the interface doesn't block, and this message is printed nevertheless.

I guess we could try to detect the backend...

**Comment by evgueni-ovtchinnikov** [comment]
a simple solution is to just prepend this message with "you may need to...", is it not?

**Comment by KrisThielemans** [comment]
simple is good!
