### ISSUE TITLE
__init__.py.tmp

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#179]
By default `CMAKE_INSTALL_PREFIX` is set to `/usr/local` on OSX. Because you would need sudo privileges to write here, this causes the error:
```
CMake Error: Could not open file for write in copy operation /usr/local/python/pGadgetron/__init__.py.tmp
```
and similar errors for pSTIR and pUtilities.

**Comment by rijobro** [comment]
@casperdcl 

Here's the full error:
```
CMake Error: Could not open file for write in copy operation /usr/local/python/pyiutilities/__init__.py.tmp
CMake Error: : System Error: No such file or directory
CMake Error at cmake/setup.py.cmake:11 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  cmake/setup.py.cmake:20 (python_pkg_alias)
  CMakeLists.txt:128 (include)
```

Presumably, it would be solved with `sudo cmake`, but this seems unusual. Could you not copy the `__init__.py.tmp` files into `CMAKE_CURRENT_BUILD_DIR` and then move them to the `CMAKE_INSTALL_PREFIX` during the install phase? Running `sudo make install` seems more normal to me than `sudo cmake`.

**Comment by casperdcl** [comment]
`*.tmp` files are never created by us, that's an intermediate CMake file. In any case, the write permissions will still be an issue.

The problem is using `configure_file` directly into an installation directory.

@KrisThielemans would prefer replacing

```cmake
configure_file(A ${CMAKE_INSTALL_PREFIX}/B)
```

with

```cmake
configure_file(A ${CMAKE_CURRENT_BUILD_DIR}/B)  # as @rijobro suggets
install(FILES ${CMAKE_CURRENT_BUILD_DIR}/B DESTINATION ${CMAKE_INSTALL_PREFIX})
```

or

```cmake
install(CODE "configure_file(A ${CMAKE_INSTALL_PREFIX}/B)")
```

?

**Comment by KrisThielemans** [comment]
there's seem to be much between these 2. I know the first option will work, the second I'm not so sure and I'd hae to study CMake more (which I won't right now!). @bathomas ?

I vote for a quick and easy solution that we can still squeeze in.

**Comment by bathomas** [comment]
I agree with @KrisThielemans. The first is what I'm more used to seeing.

**Comment by KrisThielemans** [comment]
reopened as commits broke stuff

**Comment by ashgillman** [comment]
Instead of configuring at install phase, you could configure to build directory?
