### ISSUE TITLE
Gadgetron server details are currently hardwired

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#182]
`ImagesReconstructor` etc have `localhost` and port `9002` hard-wired. We should provide functionality to let the user choose which gadgetron server to talk to.

I think it makes most sense to do this by putting `host` and `port in `GadgetChain`  and provide an accessor. Possibly have a global variable with the default server-details. For discussion...

**Comment by casperdcl** [comment]
I'd much prefer seeking for the environment variable `$GADGETRON_HOST` and `$GADGETRON_PORT`, falling back to the current `localhost` and `9002` respectively if not found.

**Comment by KrisThielemans** [comment]
sounds good to me, but maybe @DANAJK and @ckolbPTB can comment on how this is normally done with Gadgetron.

I'd also suggest to be able to set this programmatically (although maybe irrelevant as you could set the env variables from in Python/MATLAB/C++ I guess)

**Comment by DANAJK** [comment]
I believe that if you start a second Gadgetron on a machine that already has one running, it will be on port 9003. So, yes, best not to hardware the port.
