### ISSUE TITLE
forward/back project only a subset of the data

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#183]
The long term plan is to do this via #90. Possibly we need a short-cut (for PET) sooner.

**Comment by KrisThielemans** [comment]
A temporary work-around would be to use https://github.com/UCL/STIR/blob/master/src/include/stir/recon_buildblock/find_basic_vs_nums_in_subsets.h and have a version of `stir::ForwardProjectorByBin::forward_project` (and bakcprojector) that you can pass such an array to, and then just loops, and then somehow expose that in SIRF.

**Comment by evgueni-ovtchinnikov** [comment]
sorry i meant calling the new projector for a subset, not in a loop

**Comment by KrisThielemans** [comment]
ok. I think this is a temporary work-around, as it's really quite dangerous that this depends on the symmetries passed to the projector, but it'll do for now. you could even do this by letting the current `forward_project(ProjData&) call this one with `0,1` argument, and therefore have very little code changes.

Can you please also insert some error checking code (I don't know what will happen if the `num_subsets` is incompatible with the data. could/should already be in the `find_basic_vs_nums_in_subset`).

Please add a statement in the doxygen comment that this member function will disappear in a future version.

**Comment by evgueni-ovtchinnikov** [comment]
error check for num_subsets: do not know how to do it as AcquisitionModel is not aware of the number of subsets so far as i can see - this number is set later when the objective function is defined, is it not?

also, puzzled by your suggestion to pass 0, 1 for `subset_num, num_subsets` as there will be no difference from current `forward_project` then

**Comment by evgueni-ovtchinnikov** [comment]
checking num_subsets: perhaps you just meant using `subsets_are_approximately_balanced()` method?

**Comment by KrisThielemans** [comment]
checking `num_subsets`: ignore my request. `find_basic_vs_nums_in_subset` will return all possible ones, and doesn't need subsets to be balanced. This is indeed an algorithm-specific question (OSMAPOSL needs it, others not). sorry!

**Comment by KrisThielemans** [comment]
> also, puzzled by your suggestion to pass 0, 1 for subset_num, num_subsets as there will be no difference from current forward_project then

sorry to be unclear, I meant let current `forward_project` call the new one, but with `subset_num`=0, `num_subsets`=1, which then means it'll do the same as now. I hope this makes more sense :-;

**Comment by evgueni-ovtchinnikov** [comment]
even simpler: let us edit current `forward_project` prototype like this:

    void
    ForwardProjectorByBin::forward_project(ProjData& proj_data,
    const DiscretisedDensity<3,float>& image,
    subset_num= 0, num_subsets = 1);

and in the body use

    const std::vector vs_nums_to_process =
    detail::find_basic_vs_nums_in_subset(*proj_data.get_proj_data_info_ptr(), *symmetries_sptr,
    proj_data.get_min_segment_num(), proj_data.get_max_segment_num(),
    subset_num, num_subsets);

ok?

**Comment by KrisThielemans** [comment]
ok. let's put in a check then that `subset_num>=0` and `<num_subsets`. If not, call `error`.

**Comment by evgueni-ovtchinnikov** [comment]
seems to work but only for ProjData in memory; using ProjData from file throws "ProjDataFromStream: error reading data" - i am out of my depth here

**Comment by evgueni-ovtchinnikov** [comment]
pushed to branches project_subset (on UCL/STIR and SIRF) so you can try

**Comment by KrisThielemans** [comment]
regarding the error with `ProjDataFromStream`, I think this is the usual "open for read-write" issue?

**Comment by evgueni-ovtchinnikov** [comment]
then why it works for `subset_num  = 0, num_subsets = 1`?

**Comment by KrisThielemans** [comment]
hmmm. I don't know!

Can you give a description of when it breaks and the error?

**Comment by evgueni-ovtchinnikov** [comment]
it breaks if either additive or background term is present, and if i comment those out then when calling as_array method

**Comment by evgueni-ovtchinnikov** [comment]
btw as_array method essentially calls ProjData::copy_to, which looks pretty simple:

  template < typename iterT>
  std::size_t copy_to(iterT array_iter) const
  {
      iterT init_pos = array_iter;
      for (int s=0; s<= this->get_max_segment_num(); ++s)
      {
          SegmentBySinogram<float> segment= this->get_segment_by_sinogram(s);
          std::copy(segment.begin_all_const(), segment.end_all_const(), array_iter);
          std::advance(array_iter, segment.size_all());
          if (s!=0)
          {
              segment=this->get_segment_by_sinogram(-s);
              std::copy(segment.begin_all_const(), segment.end_all_const(), array_iter);
              std::advance(array_iter, segment.size_all());
          }
      }
      return static_cast<std::size_t>(std::distance(init_pos, array_iter));
  }

**Comment by evgueni-ovtchinnikov** [comment]
just found that the file created by the subset forward_project is a little shorter than the file created by full forward project: 6 076 416 vs 6 094 848 bytes (the latter being the size of the template Utahscat600k_ca_seg4.s)

i do not believe SIRF has anything to do with this

**Comment by evgueni-ovtchinnikov** [comment]
i just added fill(0.0) before forward_project (subject to num_subsets > 1), and it worked!

**Comment by KrisThielemans** [comment]
nice and simple!

can you make this optional with an extra argument? Someone might have existing data to replace a subset of the projection to. Please add relevant info to the doxygen.

I've created #185 and https://github.com/UCL/STIR/pull/217/files for this, based on your branches. When you're done, let me know and I'll accept the PR, doing the merge therefore.

**Comment by evgueni-ovtchinnikov** [comment]
done - check acquisition_model.py demo

**Comment by evgueni-ovtchinnikov** [comment]
looks like all done
