### ISSUE TITLE
error running MRI example in VM

### ISSUE THREAD

**Issue by mehrhardt** [CCPPETMR/SIRF#186]
I tried to follow the documentation given here: https://github.com/CCPPETMR/CCPPETMR_VM/wiki/Basic-usage

As I want to see what is happening I started Spyder: "You will want to see what the demos are doing. The easiest way is to use Spyder. You can start this from a terminal like this
cd $SIRF_PATH
cd examples/Python/MR
spyder fully_sampled_recon.py&
"
I thus expected that I would be able to run "fully_sampled_recon.py" in Spyder step by step.

I can confirm that I can run the demo from command line without issues.

**Comment by evgueni-ovtchinnikov** [comment]
actually you can run this demo with spyder

you apparently tried to run lines 35-37, which failed because docopt did not see lines 1-14 from which it creates args

if you run lines 1-37 then docopt will be ok

a note about this is now added to Basic Usage

**Comment by mehrhardt** [comment]
That is great; I was unfamiliar about this usage of doc-strings. I guess one cannot expect that many users will be.
