### ISSUE TITLE
help(pet.AcquisitionModelUsingRayTracingMatrix()) not clear enough

### ISSUE THREAD

**Issue by mehrhardt** [CCPPETMR/SIRF#188]
The information provided by `help(pet.AcquisitionModelUsingRayTracingMatrix())` is not clear enough to me (see below). In particular, I struggle understanding the references here like "Class for a PET acquisition model that uses (implicitly) a ray tracing matrix for G in (F)". What are G and (F)? 

From my understanding of PET and STIR, I can kind of guess what is meant: G = geometry part of projection, (F) = forward model but it would be good to make this much clearer.

Similar, what are the "additive term" and the "background term". A simple formula for (F) would make it much easier to understand.

Btw, there is a small typo: "Returns the backward projection of y giben by (B);"

> Help on instance of AcquisitionModelUsingRayTracingMatrix in module sirf.STIR:
> 
> class AcquisitionModelUsingRayTracingMatrix(AcquisitionModelUsingMatrix)
>  |  Class for a PET acquisition model that uses (implicitly) a ray tracing
>  |  matrix for G in (F).
>  |  
>  |  Method resolution order:
>  |      AcquisitionModelUsingRayTracingMatrix
>  |      AcquisitionModelUsingMatrix
>  |      AcquisitionModel
>  |  
>  |  Methods defined here:
>  |  
>  |  __del__(self)
>  |  
>  |  __init__(self, matrix=None)
>  |      Creates an AcquisitionModelUsingMatrix object, optionally setting
>  |      the ray tracing matrix to be used for projecting;
>  |      matrix:  a RayTracingMatrix object to represent G in (F).
>  |  
>  |  get_matrix(self)
>  |      Returns the ray tracing matrix used for projecting;
>  |      matrix:  a RayTracingMatrix object representing G in (F).
>  |  
>  |  set_num_tangential_LORs(self, value)
>  |      Set the number of LORs (or rays) for each bin in the sinogram.
>  |      They are currently (approximately) parallel and spaced in the
>  |      tangential direction (i.e. orthogonal to the axial direction).
>  |  
>  |  ----------------------------------------------------------------------
>  |  Methods inherited from AcquisitionModelUsingMatrix:
>  |  
>  |  set_matrix(self, matrix)
>  |      Sets the ray tracing matrix to be used for projecting;
>  |      matrix:  a RayTracingMatrix object to represent G in (F).
>  |  
>  |  ----------------------------------------------------------------------
>  |  Methods inherited from AcquisitionModel:
>  |  
>  |  backward(self, ad)
>  |      Returns the backward projection of y giben by (B);
>  |      ad:  an AcquisitionData object containing y.
>  |  
>  |  forward(self, image)
>  |      Returns the forward projection of x given by (F);
>  |      image   :  an ImageData object containing x;
>  |  
>  |  set_acquisition_sensitivity(self, asm)
>  |      Sets the normalization n in (F);
>  |      norm:  an AcquisitionSensitivityModel object containing normalisation n
>  |  
>  |  set_additive_term(self, at)
>  |      Sets the additive term a in (F);
>  |      at:  an AcquisitionData object containing a.
>  |  
>  |  set_background_term(self, bt)
>  |      Sets the background term b in (F);
>  |      bt:  an AcquisitionData object containing b.
>  |  
>  |  set_up(self, acq_templ, img_templ)
>  |      Prepares this object for performing forward and backward
>  |      projections;
>  |      acq_templ:  an AcquisitionData object used as a template for
>  |                  creating an AcquisitionData object to store forward
>  |                  projection;
>  |      img_templ:  an ImageData object used as a template for creating an
>  |                  ImageData object to store backward projection.
>

**Comment by evgueni-ovtchinnikov** [comment]
you need to look up the base class to understand the notation (help(pet.AcquisitionModel))

instructions on getting help on derived classes added to UserGuide

**Comment by KrisThielemans** [comment]
This is rather important, so I think also worth referring to the base-class doc explicitly in the message for `AcquisitionModelUsingRayTracingMatrix`. (This seems to be a limitation of the help system in Python. not sure how it looks like in MATLAB).

**Comment by evgueni-ovtchinnikov** [comment]
added references to AcquisitionData to derived classes docstrings

**Comment by KrisThielemans** [comment]
thanks!
