### ISSUE TITLE
need to import xSTIR, xGadgetron and iUtilities

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#2]
Current CMake files assume xSTIR, xGadgetron and iUtilities are subdirs of SIRF (after clone). We can do this via git submodules, but haven't done this yet. Current work-around:
git clone xSTIR, xGadgetron and iUtilities into the SIRF subdir, or add symbolic links

**Comment by casperdcl** [comment]
closed by #5
