### ISSUE TITLE
Setter for sirf::MRAcquisitionData

### ISSUE THREAD

**Issue by johannesmayer** [CCPPETMR/SIRF#203]
To set data in the simulation I would need the corresponding method `MRAcquisitionData::set_acquisition(unsigned int num, ISMRMRD::Acquisition& acq)`.

**Comment by evgueni-ovtchinnikov** [comment]
To implement this, I need to learn how to overwrite data in an hdf5 file - does anybody know?

**Comment by johannesmayer** [comment]
@evgueni-ovtchinnikov  Well for my purposes it would be enough if the `sirf::AcquisitionsVector` would provide this functionality.
For this it would be much easier to implement, right?

**Comment by evgueni-ovtchinnikov** [comment]
ok, done
