### ISSUE TITLE
Memory Leak in sirf::AcquisitionsVector

### ISSUE THREAD

**Issue by johannesmayer** [CCPPETMR/SIRF#204]
The class `sirf::AcquisitionsVector` has a memory leak.
Loop constructions such as
```
AcquisitionsVector all_acquis = some acquisitions vector filled with data and acquisitions info.

AcquisitionsVector temp_dummy_vector;
temp_dummy_vector.copy_acquisitions_info(all_acquis);
ISMRMRD::Acquisition acq;
for(size_t i_acq=0; i_acq<all_acquis.number(); i_acq++)
{
    all_acquis.get_acquisition(i_acq, acq);
    temp_dummy_vector.append_acquisition(acq);
}
```
whereas replacing 
```
ISMRMRD::Acquisition acq;
for(size_t i_acq=0; i_acq<all_acquis.number(); i_acq++)
{
    all_acquis.get_acquisition(i_acq, acq);
    temp_dummy_vector.append_acquisition(acq);
}
```
by
```
for(size_t i_acq=0; i_acq<all_acquis.number(); i_acq++)
{
    ISMRMRD::Acquisition acq;
    all_acquis.get_acquisition(i_acq, acq);
    temp_dummy_vector.append_acquisition(acq);
}
```
does not generate a leak.

**Comment by evgueni-ovtchinnikov** [comment]
just checked - the same happens if we use `std::vector<ISMRMRD_Acquisition>`

so it must be `std::vector` idiosyncrasy, not `shared_ptr`

**Comment by evgueni-ovtchinnikov** [comment]
or else something wrong with `ISMRMRD_Acquisition` assignment

**Comment by KrisThielemans** [comment]
has this been resolved?

**Comment by evgueni-ovtchinnikov** [comment]
@johannesmayer: do you still have this leak?

**Comment by johannesmayer** [comment]
I did not investigate any further into this matter. So I guess the bug is still present.

**Comment by evgueni-ovtchinnikov** [comment]
i can no longer reproduce this leak - perhaps, ismrmrd was updated recently?

**Comment by johannesmayer** [comment]
I let the my testjob run again (code below), and this leak is still present.

The following snippet should need a huge amount of memory, whereas setting `construct_inside_loop=true` will lead to freeing of memory after each iteration of the `for` loop.
(`ISMRMRD_H5_TEST_PATH` needs to point to a valid ISMRMRD file location of course).
The only difference between `construct_inside_loop =true/false` is where the line `		ISMRMRD::Acquisition acq;` is put, once outside, once inside the loop.
Also, the `Acquisition` object is not processed in any way, just as an argument in the `get_acquisition` method.
```
AcquisitionsVector all_acquis;
all_acquis.read( std::string( ISMRMRD_H5_TEST_PATH ));

size_t num_iterations = 1000;

bool construct_inside_loop = false;
	
if( construct_inside_loop )
{
    for(size_t i=0; i<num_iterations; i++)
    {
	std::cout << "loopindex i " << i <<std::endl;

	for(size_t i_acq=0; i_acq<all_acquis.number(); i_acq++)
	{	
		ISMRMRD::Acquisition acq;
                all_acquis.get_acquisition(i_acq, acq);
	}
    }
}
else
{
    for(size_t i=0; i<num_iterations; i++)
    {
	std::cout << "loopindex i " << i <<std::endl;

	ISMRMRD::Acquisition acq;
	for(size_t i_acq=0; i_acq<all_acquis.number(); i_acq++)
	{	
            all_acquis.get_acquisition(i_acq, acq);
	}
   }
}
```

I use the devel build with `ISMRMRD_TAG` set to v1.4.0.
I cannot find how to reopen the issue, maybe somebody else could.

**Comment by KrisThielemans** [comment]
@johannesmayer @evgueni-ovtchinnikov what's the status of this?

**Comment by johannesmayer** [comment]
It still exists but I didn't investigate any further!

**Comment by KrisThielemans** [comment]
could we try and remove SIRF and check if it's an ISMRMRD problem? Something like this
```C++
std::vector<std::shared_ptr<ISMRMRD::Acquisition> > all_acquis = some acquisitions vector filled with data

std::vector<std::shared_ptr<ISMRMRD::Acquisition> > temp_dummy_vector;
ISMRMRD::Acquisition acq;
for(size_t i_acq=0; i_acq<all_acquis.size(); i_acq++)
{
    acq = *all_acquis[i_acq];
    temp_dummy_vector.push_back(std::shared_ptr<ISMRMRD::Acquisition>
				(new ISMRMRD::Acquisition(acq)));
}
```

**Comment by johannesmayer** [comment]
Yeah you are right, I don't know why I didn't do this earlier.
So the code below yields a very quick memory overflow of more than 50GB RAM if the parameter `construct_inside_loop = false` and does not generate the leak if set to `true`.

````
size_t num_iterations = 1000;

size_t num_acquis = 256*128;
uint16_t num_samples = 192;
uint16_t num_channels = 32;
		
ISMRMRD::Acquisition acq(num_samples, num_channels);
std::vector< std::shared_ptr<ISMRMRD::Acquisition> > acq_vec;
for (int i = 0; i < num_acquis; ++i)
{
    acq_vec.push_back(std::make_shared<ISMRMRD::Acquisition>(acq));	
}

bool construct_inside_loop = false;

if( construct_inside_loop )
{
for(size_t i=0; i<num_iterations; i++)
{
    std::cout << "loopindex i " << i <<std::endl;
	
    for(size_t i_acq=0; i_acq<acq_vec.size(); i_acq++)
    {	
        ISMRMRD::Acquisition temp_acq;
        temp_acq = *acq_vec[i_acq]; 
    }
}} 
else
{
    for(size_t i=0; i<num_iterations; i++)
    {
    std::cout << "loopindex i " << i <<std::endl;

    ISMRMRD::Acquisition temp_acq;
    for(size_t i_acq=0; i_acq<acq_vec.size(); i_acq++)
    {	
        temp_acq = *acq_vec[i_acq]; 
    } 
}}
````

**Comment by KrisThielemans** [comment]
ah, that's even weirder. now there's no longer another `make_shared` inside the loop! Seems that `ISMRMRD::Acquisition::operator=` leaks for existing objects.

It seems to me that you could now simplify this even more by dispensing with the `acq_vec` and just always assigning `acq`.

In any case, this is therefore an ISMRMRD bug. Care to create the bug report there yourself? (ideally quoting this issue). Or we could do it for you.

once there's an ISMRMRD issue, we'll close the SIRF one, as it's out of our control.

thanks!

**Comment by johannesmayer** [comment]
Haha, ok, they apparently fixed it in 15 seconds in their latest commit.

**Comment by KrisThielemans** [comment]
great! probably best to let them know that it was fixed and close their issue.

I've asked them if they would consider creating a new release https://github.com/ismrmrd/ismrmrd/issues/136.

I'll close this one now. thanks for your persistence!

**Comment by johannesmayer** [comment]
They fixed it themselves, I had no idea what was wrong there.
They also had a similar issue in their image constructor. I guess they keep the issue open until they are sure all other classes are fine and will then close it.
