### ISSUE TITLE
Virtual methods of SIRFImageDataDeformation are missing

### ISSUE THREAD

**Issue by johannesmayer** [CCPPETMR/SIRF#206]
@rijobro No worries this linking error is well behaved!!!

The inheritance in the SIRFReg module is done as:

`class SIRFImageDataDeformation : public SIRFImageData`

However, 
````
/// SIRF image data
class SIRFImageData
{
...
public:
 /// Destructor
virtual ~SIRFImageData() {}

/// Assignment
 virtual SIRFImageData operator=(const SIRFImageData& to_copy);

...
}
````
contains virutal methods which are not defined for the child `SIRFImageDataDeformation`.
This creates a linking error. 
Also since two of them are already there, I stumbled upon this thing here: [https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)](url) 

Maybe it would be a good idea to define the copy constructor as well for this class.

**Comment by rijobro** [comment]
@johannesmayer, see this paragraph I found online:

> "In C++, just because you think that a particular function call is bound late doesn’t mean that it is. If not declared with the same arguments in the subclasses, the member functions are not overridden polymorphically, whether or not they are declared virtual."

So I would expect `SIRFImageDataDeformation` to use the `SIRFImageData` copy constructor, which is fine, since `SIRFImageDataDeformation` doesn't contain any extra members.
