### ISSUE TITLE
create an AcquisitionData from scratch (without a file)

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#21]
provide simple interface to STIR capabilities to create an AcquisitionData. A new constructor maybe like
```
AcquisitionData('scanner_name',span=1,max_ring_difference=-1,view_mash_factor=1)
```
with the default for `max_ring_difference` meaning to use the maximu for that scanner and span.

Can we just force  arc_correction=false?

**Comment by KrisThielemans** [comment]
STIR methods to use

- construct scanner from string. Scanner::get_scanner_from_name
- construct ProjDataInfo from scanner: ProjDataInfo::ProjDataInfoCTI. will need to get 
  - num_views=scanner.get_num_detectors_per_ring()/2/view_mash_factor
  - num_tangential_poss=scanner.get_max_num_non_arccorrected_bins() 
  - if (max_ring_difference<0) max_ring_difference=scanner.get_num_rings()-1

**Comment by KrisThielemans** [comment]
use [stir::ProjDataInfo::construct_proj_data_info](https://github.com/UCL/STIR/blob/f9a93a73dc0ee6ed7495fa92991a58264f9378c6/src/include/stir/ProjDataInfo.h#L100) (`ProjDatInfoCTI` is now outdated)

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov, this should help for the `ListmodeToSinogram` template.

**Comment by evgueni-ovtchinnikov** [comment]
The constructor also needs ExamInfo I believe.

**Comment by KrisThielemans** [comment]
yes sure. can use a default constructed one for now. will have to add patient info later.

**Comment by evgueni-ovtchinnikov** [comment]
done
