### ISSUE TITLE
Memory leak in SIRFImageData

### ISSUE THREAD

**Issue by johannesmayer** [CCPPETMR/SIRF#210]
There is a memory leak using the SIRFImageData constructor.
The following short program leads to a memory overflow despite the newly initialized object goes out of scope immidiately:

```
#include <stdio.h>
#include "SIRFImageData.h"

int main(  )
{
    #define DISPLACEMENT_FIELD_PATH "filename_nifti_with_extension"

    typedef SIRFImageData ImageType; 
    size_t const num_cycles = 10000000;

    for(size_t i_cycle=0; i_cycle<num_cycles; i_cycle++)
    {
	std::cout << "Cycle: " << i_cycle+1 << "/" << num_cycles << std::endl;
	ImageType temp_img(DISPLACEMENT_FIELD_PATH);				
    }
    return 0;
}
```
@KrisThielemans 
The SIRFImageData interface can be found at [https://github.com/CCPPETMR/SIRF/blob/SIRFReg/src/Registration/cReg/SIRFImageData.h](url)

There is no destructor explicitly defined for the class. Is this what makes it go wrong?

Invoking a desturctor such as:

``` virtual ~SIRFImageData() { nifti_image_unload( _nifti_image.get() ) ;} ``` 

makes the above example not overflow but leads to segmentation faults in applications afterwards, so this does apparently not solve it neither.

**Comment by johannesmayer** [comment]
Ok I rewrote my code s.t. a set of 10 images are read in once, and then 'pushed_back' into a vector and kept in memory. This way the read-function is called once only.

`std::vector<T>::push_back(T&)` uses the copy constructor which in this case is compiler-generated.

However, now the memory still overflows.

**Comment by KrisThielemans** [comment]
the read function needs to be corrected of course, but show us the new code then

**Comment by johannesmayer** [comment]
Now employing the `SIRFImageData` (or child classes, in this case `SIRFImageDataDeformation`) cause problems when used in other SIRFReg classes.
This causes memory overflow:

- read image from file
- use (compiler generated!) copy constructor to create `SIRFImageDataDeformation`
- pass it to object `SIRFRegImageWeightedMean4D` and process them
- push_back to `vector<ImageType>`

Even though the vector and the images go out of scope all the time the memory overflows and the read function is only called one single time.

```
typedef SIRFImageDataDeformation ImageType; 
size_t const num_cycles = 10000;
size_t const num_composed_deformations = 2;
ImageType img_from_file(DISPLACEMENT_FIELD_PATH);				
		
for(size_t i_cycle=0; i_cycle<num_cycles; i_cycle++)
{
	std::vector<ImageType> deformation_container;
	std::cout << "Cycle: " << i_cycle+1 << "/" << num_cycles << std::endl;

	for(size_t i_deformation=0; i_deformation<num_composed_deformations; i_deformation++)
	{
		ImageType temp_img(img_from_file);				
					
		SIRFRegImageWeightedMean4D dvf_interpolator;
	    
    		dvf_interpolator.add_image( temp_img, 0.5);
    		dvf_interpolator.add_image( temp_img, 0.5);

   		dvf_interpolator.update();
    
    		SIRFImageDataDeformation output_deformation = dvf_interpolator.get_output();
 		deformation_container.push_back(output_deformation);
	}
}// each cycle the vector should go out of scope
```

**Comment by rijobro** [comment]
Hi Johannes,

I replaced the line that Kris mentioned with:


    nifti_image *im = nifti_image_read(filename.c_str(), 1);

    image = std::shared_ptr<nifti_image>(im, nifti_image_free);

And this seems to have solved the problem. The second argument of the second line is the deleter, which tells the shared_ptr what to do when its use count reaches zero and it needs to be deleted.

I’ll push that change now, let me know if that solves your problem.

@Kris, I’ll delete the raw pointer constructor.

Richard

On 6 Sep 2018, at 16:52, johannesmayer <notifications@github.com<mailto:notifications@github.com>> wrote:


Now employing the SIRFImageData (or child classes, in this case SIRFImageDataDeformation) cause problems when used in other SIRFReg classes.
This causes memory overflow:

  *   read image from file
  *   use (compiler generated!) copy constructor to create SIRFImageDataDeformation
  *   pass it to object SIRFRegImageWeightedMean4D and process them
  *   push_back to vector<ImageType>

Even though the vector and the images go out of scope all the time the memory overflows and the read function is only called one single time.

typedef SIRFImageDataDeformation ImageType;
size_t const num_cycles = 10000;
size_t const num_composed_deformations = 2;
ImageType img_from_file(DISPLACEMENT_FIELD_PATH);

for(size_t i_cycle=0; i_cycle<num_cycles; i_cycle++)
{
        std::vector<ImageType> deformation_container;
        std::cout << "Cycle: " << i_cycle+1 << "/" << num_cycles << std::endl;

        for(size_t i_deformation=0; i_deformation<num_composed_deformations; i_deformation++)
        {
                ImageType temp_img(img_from_file);

                SIRFRegImageWeightedMean4D dvf_interpolator;

                dvf_interpolator.add_image( temp_img, 0.5);
                dvf_interpolator.add_image( temp_img, 0.5);

                dvf_interpolator.update();

                SIRFImageDataDeformation output_deformation = dvf_interpolator.get_output();
                deformation_container.push_back(output_deformation);
        }
}// each cycle the vector should go out of scope

**Comment by rijobro** [comment]
https://github.com/CCPPETMR/SIRF/commit/c334d3122a4ef574ee606e71cf42c07b72a25f52 should solve this.
