### ISSUE TITLE
image data structure

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#212]
Here are is the proposed data structure in SIRF. Feel free to comment any thoughts down below. 

# Inheritance hierarchy (from base to derived)
- `DataContainer`
- `SIRFImageData`
- `PETImageData` / `MRImageData` / `NiftiImage`

# `DataContainer`
Represents both images and acquisition data. Should contain the following aspects:
- Exam_info (timing, etc)
- Algebra
- Fill / as_array methods

# `SIRFImageData`
All images in SIRF. They should be templated for voxel type. e.g., scalar for images and coordinates for deformations. Should contain the following aspects:
- Geometrical info (this currently lives in `PETImageData`)
- Abstract methods for getting start and end iterators of data.

# `PETImageData` / `MRImageData` / `NiftiImage`
Constructors should take `SIRFImageData` as argument. They call the start and end iterators of the `SIRFImageData`, and can copy the data as necessary to construct themselves. They would also copy the geometrical_info. In this way, we can convert any image type to any other image type. Creating a `NiftiImage` from an `MRImageData` would cause a loss of information (because not all information present in `MRImageData` is needed by `NiftiImage`), so we couldn't then copy the `NiftiImage` back to the `MRImageData`. For this reason, use the `fill` method to get data back after a process.

# Pseudo code
 ```
PETImageData im=recon.get_output();
NiftiImage nifti_im(im);
# Do some resampling/registration
im.fill(nifti_im);
```

**Comment by ashgillman** [comment]
### Naming
If we are changing the names and hierarchy anyway, does it add anything to the names to have 'Data' appended to every name? Its probably just as instructive to have SIRFImage, PETImage, MRImage, etc.

---

### SIRFImageData Responsibility
>>> Abstract methods for getting start and end iterators of data.

Probably this should also go in `DataContainer`

---

Apart from those tiny suggestions, I think this looks good.

**Comment by rijobro** [comment]
@ashgillman  I agree with both those points, although the first would unnecessarily break backwards compatibility.

**Comment by rijobro** [comment]
This issue also relates to the incluison of the geometrical info PR, #193.

**Comment by KrisThielemans** [comment]
I veto renaming `ImageData` to `Image`. Reasons:
- serious backwards compatibliity break, including with CIL (who have adapted our terminology)
- we have `AcquisitionModel`, `AcquisitionData`, `ImageData`. makes sense
- 'ImageData` to tell people it's more than an image (i.e. most people think about that as a bunch of numbers). But I guess you could look at it the other way of course.

**Comment by rijobro** [comment]
I suppose I'll rename `NiftiImage` to `NiftiImageData` to match with the rest of SIRF then.

**Comment by ashgillman** [comment]
Sounds good, I was originally going to make @rijobro's last comment but went for the big bite.

**Comment by rijobro** [comment]
Do we first need to finish PR #193 before we can start on this?

**Comment by evgueni-ovtchinnikov** [comment]
First of all we need to sort out the data submodule conflict - @casperdcl can you please implement the agreed course of action (as per KT e-mail of Oct 10 at 21:03) and let us know when done?

**Comment by ashgillman** [comment]
Re #193, I think this PR should come first, and then I'll rebase the other. This change is less disruptive than the other.

**Comment by rijobro** [comment]
So we implement the `SIRFImageData` without any `GeometricalInfo`?

**Comment by rijobro** [comment]
That would be a bit of a shame as we wouldn't be able to put in any methods that require `GeometricalInfo`. Tricky...

**Comment by casperdcl** [comment]
> - [x] 1. SIRF: create a new commit on top of master to point the submodule the new top of CCPPETMR/SIRF_data@cd139a1c69fafb0b2126495d8716c0ee3e38c9dd
> - [x] 2. Remove the last commit CCPPETMR/SIRF_data@09ca932ed027af3567d06fc47855b2a0d0ca7e7d, force push
> - [ ] 3. Document somewhere (either wiki or CONTRIBUTING.md I guess) how to update SIRF_data, how to update the submodule, and what happens when switching branches
> - [ ] 4. Merge master to devel
> - [ ] 5. Write an email to the devel list.

**Comment by KrisThielemans** [comment]
@casperdcl, the above list shouldn't be in this issue. Can you move it to a new one? sorry

**Comment by rijobro** [comment]
@evgueni-ovtchinnikov, do you think you could implement the bare bones of this structure now that Casper has done the submodule. After that, we need to incorporate `GeometricalInfo` into the newly created `SIRFImageData`, and then I can work on being able to populate `GeometricalInfo` from `NiftiImageData`

**Comment by evgueni-ovtchinnikov** [comment]
working on it

**Comment by rijobro** [comment]
Great, thanks!

**Comment by KrisThielemans** [comment]
I don't think we should this the base class `SIRFImageData`, but just `ImageData`. It already lives in the `sirf` namespace.

**Comment by KrisThielemans** [comment]
See #226
