### ISSUE TITLE
more complete image IO

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#22]
we need to be able to read images and write. we will rely on underlying functionality of STIR and Gadgetron as usual, but currently not much of that is exposed.

**Comment by KrisThielemans** [comment]
done, but needs demo

**Comment by evgueni-ovtchinnikov** [comment]
Python demos now cover all 8 IO facilities (R|W*Acq|Img*PET|MR).

Matlab catch-up to be a separate issue, so closing this one.
