### ISSUE TITLE
Fill GeometricalInfo from ISMRMRD

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#221]
We need to be able to fill in all the required fields in `GeometricalInfo` from ISMRMRD. 

In this way, once the new data structure has been implemented (#212), we'll be able to convert between image types. 

We have the phantom data (@bathomas), I think we'll need your help @johannesmayer and @DANAJK.

**Comment by DANAJK** [comment]
A possible plan for checking that the geometry info in ISMRMRD corresponds to the reconstructed image would be:
Select some datasets from those acquired.
Convert to ISMRMRD
Recon using SIRF
Make minimal DICOM from SIRF recon and geom info in ISMRMRD
Resample this DICOM to be nominally same as scanner’s DICOM and compare.
 
Another thing is if someone could find in the siemens_to_ismrmrd source code how it sets the bed offset value – the reported values in the tens of thousands are puzzling.

**Comment by johannesmayer** [comment]
I did check the code from the converter software: 
It just straight copies elements from the siemens .dat header into the location in the 

```
ismrmrd_acq.patient_table_position()[0]  = (float)scanhead.lPTABPosX;
ismrmrd_acq.patient_table_position()[1]  = (float)scanhead.lPTABPosY;
ismrmrd_acq.patient_table_position()[2]  = (float)scanhead.lPTABPosZ;
```
(from ismrmrd/siemens_to_ismrmrd/main.cpp)

**Comment by KrisThielemans** [comment]
@rijobro, can you document current status on this? Hopefully close it... (please reference commit)

**Comment by KrisThielemans** [comment]
all done
