### ISSUE TITLE
MRAcquisitionData::write forgets lots of important data

### ISSUE THREAD

**Issue by johannesmayer** [CCPPETMR/SIRF#225]
The class method definition `MRAcquisitionData::write(...)` in `gadgetron_data_containers.cpp`  contains a statement 
```
for (int i = 0; i < n; i++) {
		get_acquisition(i, a);
		if (TO_BE_IGNORED(a)) {
			continue;
		}
		mtx.lock();
		dataset->appendAcquisition(a);
		mtx.unlock();
	}
```
where `TO_BE_IGNORED(a)` is defined as a selective list excluding some acquisition types such as noise calibration etc. ( also mentioned in the documentation ):
```
#define TO_BE_IGNORED(acq) \
	(!(acq).isFlagSet(ISMRMRD::ISMRMRD_ACQ_IS_PARALLEL_CALIBRATION) && \
	!(acq).isFlagSet(ISMRMRD::ISMRMRD_ACQ_IS_PARALLEL_CALIBRATION_AND_IMAGING) && \
	!(acq).isFlagSet(ISMRMRD::ISMRMRD_ACQ_LAST_IN_MEASUREMENT) && \
	(acq).flags() >= (1 << (ISMRMRD::ISMRMRD_ACQ_IS_NOISE_MEASUREMENT - 1)))
```
However, this is probably a bit of a flawed concept! This list of flags is not complete and will never be!
For example this list excludes echoes with inverted readout ( standard for multi-echo acquisitions in MRI ) and thus half of the data!
Rather the reader function should take care of ignoring acquisitions not necessary for reconstruction instead of the writer!

**Comment by KrisThielemans** [comment]
@johannesmayer, you are probably correct, but I think it's better to raise questions and make suggestions, than to make somewhat emphatic criticism :-; I guess you must have been frustrated!

**Comment by johannesmayer** [comment]
I am sorry, you are entirely correct. It was not very nice and I don't know what these exclams are doing there... sorry again... :-( 

I would write out all acquisitions there are in memory, otherwise one might lose things accidentally, and hence cut the line 
```
if (TO_BE_IGNORED(a)) {
			continue;
		}
```
in the `MRAcquisitionData::write()` function.
I will do this and make a fix and PR on this but I wanted to ask before if there is any reason why this might break things? 

Because as far as I could see there is no reading methods provided for the `MRAcquisitionData`, rather this is performed by a reading gadget during reconstruction. (is this correct?)

Are there restrictions on array shape and number of dimensions on the SIRF side, for which intentionally only the acquisition flags not ignored by the writer can be reconstructed, that would prohibit writing out all the data?
