### ISSUE TITLE
PET Poisson objective function and acquisition data

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#23]
current code looks like
```
obj_fun = pStir.make_Poisson_loglikelihood(acquired_data)
obj_fun.set_acquisition_model(am)
obj_fun.set_acquisition_data(acquired_data)
```
It is confusing to use `acquired_data` twice. However, `pStir.make_Poisson_loglikelihood` actually ignores the first argument. It seems to make sense to let it set the acquisition data directly.

Also, without `set_acquisition_data`, the code currently silenty crashes. This needs a fix in STIR.

**Comment by evgueni-ovtchinnikov** [comment]
Moved set_acquisition_data() call to make_Posson_loglikelihood().

**Comment by KrisThielemans** [comment]
SIRF is now fixed. STIR still needs a check on set_acquisition_data.

**Comment by KrisThielemans** [comment]
STIR is updated now and merged to CCPPETMR fork
