### ISSUE TITLE
removing SRC_PATH

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#24]
The SRC_PATH environment variable is almost obsolete. It's used by the (old) Makefiles, and in pUtil.py as a fall-back if SIRF_PATH isn't defined. However, that fall-back doesn't exist for MATLAB.

Let's remove SRC_PATH from pUtil.py ? (I'll already remove it from INSTALL.txt)

**Comment by evgueni-ovtchinnikov** [comment]
Done on devel.
