### ISSUE TITLE
hackathon 2 preparation

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#249]
- [ ]	add registered people to hackers group such that they have write access to the hackathon repos
- [ ] make sure there are no PRs in hackathon repos if at all possible. Outstanding issues should be moved to the main repos ([might be possible now](https://blog.github.com/changelog/2018-10-30-issue-transfer/). Can projects be (re)moved (not essential)?
- [ ] merge main repo master to hackathon repo (just before the hackathon)

**Comment by KrisThielemans** [comment]
@pwadhwa351 @bathomas @NikEfth there are a few issues/projects in https://github.com/CCPPETMR/Hackathon-STIR/. I guess these can be deleted?

**Comment by KrisThielemans** [comment]
I think we can just re-use the hackathon1 group (which might then need renaming)

**Comment by pwadhwa351** [comment]
Yes these can be deleted and re-used for Hackathon-2. I will delete them now.


________________________________
