### ISSUE TITLE
Updating boost creates trouble for an existing installation

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#257]
`FindBoost` creates cached variables for the boost libraries it found (to save time). That means that if you afterwards update Boost, it might still link with the old versions, while more recent include files are found. That will likely linking errors or crash boost functions from those libraries.

**Comment by KrisThielemans** [comment]
This could be a CMake issue, but is likely caused by the fact that we repeat `find_package(Boost ...)` in multiple places, each time with different libraries, e.g. for at the [top level](https://github.com/CCPPETMR/SIRF/blob/163c3a6de58ca76d8167d94858fcdace898f352d/CMakeLists.txt#L69) without libraries, and in [mGadgetron](https://github.com/CCPPETMR/SIRF/blob/163c3a6de58ca76d8167d94858fcdace898f352d/src/xGadgetron/mGadgetron/CMakeLists.txt#L21), etc. This strategy runs the risk that each `find_package` finds different libraries.

I believe we therefore need to put all `find_package(boost ...)` statements in one go at the top-level.

**Comment by rijobro** [comment]
closed via #288.

**Comment by rijobro** [comment]
only partially solved

**Comment by KrisThielemans** [comment]
let's document this on the wiki (upgrade section presumably)

**Comment by rijobro** [comment]
Documented here: https://github.com/CCPPETMR/SIRF/wiki/Rebuilding-after-upgrades#upgrading-boost-versions
