### ISSUE TITLE
FindOPENMP changed since CMake 3.9 (older version breaks SIRFReg)

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#259]
Since [CMake 3.9](https://cmake.org/cmake/help/v3.9/module/FindOpenMP.html), FindOPENMP has `OpenMP_<lang>_FOUND` and defines the `OpenMP::OpenMP_<lang>` target. Before that, [it had](https://cmake.org/cmake/help/v3.8/module/FindOpenMP.html) `OPENMP_FOUND` and `OpenMP_CXX_FLAGS` (and no link flag, causing a bug on some systems for linking).

This breaks [our lines to accomodate OpenMP and NiftyReg](https://github.com/CCPPETMR/SIRF/blob/ce42aeb1ea710caf99f1169a36655b3fe6e31728/src/Registration/cReg/CMakeLists.txt#L41)

As we'll have [boost problem dependencies etc](https://github.com/CCPPETMR/SIRF-SuperBuild/issues/162) with older CMake as well, I suggest we up to requirements to CMake 3.9. Objections?

**Comment by KrisThielemans** [comment]
@rijobro, only thing that needs to happen is up requirement for CMake version to 3.9.0 (and therefore edit installation instructions and CHANGES.md)

**Comment by rijobro** [comment]
Ok

**Comment by KrisThielemans** [comment]
fixed by #331
