### ISSUE TITLE
exception processing for STIR

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#26]
Exceptions aren't properly caught. When reading a non-existent file I get in MATLAB

```
ERROR: ProjData::read_from_file: error opening file
```
but the exception thrown has as message
```
??? unhandled exception exception thrown at line 202 of C:\Users\krisf\Documents\devel\SIRF\src\xSTIR\cSTIR\cstir.cpp
```
which will confuse nearly everyone.

In Python, the STIR error isn't shown (but the exception message is the same of course).

Also, the error id of the exception is `AcquisitionData:error`. Any chance this can be made more specific? (this could be fixed later)
```

**Comment by casperdcl** [comment]
I guess this depends. If we're relying on `swig` to wrap C(++)-code we'll have to look into swig exception handling

**Comment by evgueni-ovtchinnikov** [comment]
We do not use swig exception handling at present. Exceptions are caught by C interface (cSTIR, cGadgetron) and recorded in the _status property of the DataHandle object passed to SIRF Python/Matlab interface modules, which have status-checking functions.

The plan was that STIR throws a special exception object LocalisedException containing information on where it was thrown, but we have not implemented it yet: STIR still throws a string exception from its function error(), and it is not possible to tell where the error actually occurred.

For now, I just added catching a string exception to the C interface.
