### ISSUE TITLE
Add 3D FFT capabilities in MRAcquisitionModel

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF#267]
At present, MRAcquisitionModel forward projection works with 2D coil images obtained from the 2D slice-arranged acquisition data by 2D FFT. However, this does not work for raw data that involve kspace encoding step 2 and needs 3D FFT.

**Comment by johannesmayer** [comment]
Hey Evgueni,

I am on this as well, we should discuss this.
On my fork I modified the `fwd_()` method of the `MRAcquisitionModel` and I implemented some code on this for example in this file, using Gadgetron FFT code to encode 3D image data.

https://github.com/johannesmayer/SIRF/blob/devJohannes/src/xGadgetron/cGadgetron/encoding.h

**Comment by evgueni-ovtchinnikov** [comment]
Hi Johannes,

(Sorry for replying late to your comment - got distracted by some other stuff.)

Glad to hear you already succeeded in using 3D FFT!

I see though that you are apparently using Gadgetron libraries - unfortunately we cannot, as we still have not succeeded in installing Gadgetron under Windows. (This is why I assigned this issue to Milestone 3.0.)

**Comment by johannesmayer** [comment]
Ah ok, I see.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov I think done? Please close but write which PR or commit.

**Comment by evgueni-ovtchinnikov** [comment]
fixed by 56561a3a3e176179bc0068f8015c3f0fe2f8cd36
