### ISSUE TITLE
Reconstructing spatial calibration phantom gives 93 image slices

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#271]
I reconstructed the sagittal MR-acquisition of the spatial calibration phantom. The workflow was basic:

1. `siemens_to_ismrmrd` to get the `.dat` file
2. `python fully_sampled_recon.py` (from the SIRF examples)

Looking at the meta-data of the reconstructed image in HDFView, I can see that the image consists of 31 slices. However, as I load it into SIRF with:
```
pGadgetron.ImageData('recon.h5')
```
I see the output:
```
group dataset
variable image_0
number of images: 93
image data type: 7
```
I wrote a simple method that loops over each slice and prints all the variables in ISMRMRD::ImageHeader. Looking at it, the data repeats every 31 entries (even the time stamps are the same). Does anyone know why this might happen?

You can find the .csv with the metadata for all 93 images attached - [image_metadata.txt](https://github.com/CCPPETMR/SIRF/files/2699195/new_output.txt). This is saved as a `.txt`, so simply change the extension to `.csv` and you should be able to view it. 

The data, should you want to reconstruct it yourself (please do!), is available on my OneDrive - [here](https://liveuclac-my.sharepoint.com/:f:/g/personal/rmharbr_ucl_ac_uk/EiDe-kFIvmtAmwi2bNmXOJwBJqHk8AAqJ32YUb08LsPIYw?e=EYqv2M).

**Comment by DANAJK** [comment]
Did you run gadgetron 3 times? It can concatenate results.

**Comment by rijobro** [comment]
Yes! Thanks. 

I'm surprised that the images get concatenated, but I suppose that's just something I'll have to remember.
