### ISSUE TITLE
Geometrical Info for GadgetronImagesVector

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#272]
This carries on from #193 (new issue since it's specific to MR).

With @DANAJK and @evgueni-ovtchinnikov , we had a go at populating the necessary metadata to be able to convert to and from ISMRMRD images. If you want to see the code, check `GadgetronImagesVector::set_up_geom_info()` in `gadgetron_data_containers.cpp` in the SIRFReg branch.

From the geometrical info class, we need to extract the following information from images:
1. number of voxels (size)
2. spacing
3. transformation matrix
4. offset

The first two have been implemented (and it would be good if you could confirm the logic), and the last two need to be implemented.

### Size
We determined the number of voxels from `matrix_size[0]`, `matrix_size[1]` and `this->number()`. 

We used `this->number()` as opposed to `matrix_size[2]` as this gives us the number of slices present.

### Spacing
For spacing, we used the FOV (mm) divided by the number of voxels in the x- and y-directions. 

In the z-direction, we use the distance between neighbouring voxel centres. This is done by calculating the dot product between `position` and `slice_dir` for two consecutive slices and taking the difference.

### Transformation matrix
I'm not sure about this one. We know that the images are sorted such that (I hope I haven't got x and y mixed up):
- `x`=`read_dir`
- `y` = `phase_dir`
- `z` = `slice_dir`

These are orthogonal to each other, so presumably the transformation matrix can be calculated from that?

### Offset
Looking at the code for the `STIRImageData`, offset is the LPS location of the first voxel. Can we use `position` for the first slice (I guess this will give the centre of that slice) and move in half the FOV in the `read_dir` and `phase_dir` directions (along the hypotenuse) to get to the corner of the image. The offset would then just be the sum of these vectors?

**Comment by KrisThielemans** [comment]
@rijobro Done now?

**Comment by rijobro** [comment]
Something has been implemented, but I'm not 100% it's correct (still unable to go from Gadgetron to nifti).

**Comment by KrisThielemans** [comment]
done
