### ISSUE TITLE
clone in DataContainer

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#280]
The cloning of `DataConatiner`s was discussed in #278. It was implemented for `ImageData` in #277, but has not been lifted up to `DataContainer` (and therefore all of the `AcquisitionData` child classes). This therefore needs to be done.

These methods should also be called by the matlab/python code (for all `DataContainers` - images and acquisition data).

**Comment by rijobro** [comment]
Closing, as similar to #278

**Comment by rijobro** [comment]
Re-opening as it's only been implemented for `ImageData` downwards, not `DataContainer` yet.

**Comment by evgueni-ovtchinnikov** [comment]
closed with 8db334f11a6352350651f85dabbabe9256e1649d
