### ISSUE TITLE
Name Enums SIRF-specific

### ISSUE THREAD

**Issue by johannesmayer** [CCPPETMR/SIRF#282]
In the file `nifit1.h` included via SIRFReg functionality there is a set of macros defined as 
```
#define DT_NONE                  
#define DT_UNKNOWN           
... 
``` 
which clashes with `enum`-definitions containing the same names, e.g. 
```
enum SomeEnumName
{
   DT_NONE = 0,
   DT_UNKNOWN = 0
...
};
```
that appear in other headers that are included (such as the `<gadgetron/ImageBaseIO.h>` header from Gadgetron).  Inclusion of both headers yields compilation errors.

**Comment by KrisThielemans** [comment]
Created https://github.com/gadgetron/gadgetron/issues/727. This is not a SIRF issue.
