### ISSUE TITLE
travis failure on OSX because of time-out when building ITK

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#286]
our last job always fails at 50mins. It's try to build ITK, which takes ages of course. I suggest we use
```
brew install insighttoolkit
```
@rijobro @bathomas would this work?

**Comment by rijobro** [comment]
Do you know more specifically how to do this? [This](https://blog.kitware.com/kitware-packages-on-os-x-with-homebrew/) blog post gave these instructions:

```
brew tap homebrew/homebrew-science
brew install insighttoolkit
```

But the first line gives the following error:

```
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
```

And the second line by itself gives:

```
Error: No formulae found in taps.
```

Looking at the Travis log - it looks like we're quite close to the end of the compilation. Could we just minimise the number of ITK modules compiled to a minimum?

**Comment by rijobro** [comment]
> Could we just minimise the number of ITK modules compiled to a minimum?

STIR is the only package that needs ITK, so if we were to do this could we change the line in STIR's `CMakeLists.txt` from:

```
find_package(ITK QUIET)
```

to:
```
find_package(ITK QUIET whichever_libaries_needed)
```
?

**Comment by KrisThielemans** [comment]
very good idea! However,not sure which components we need in all honesty, but probably only IO (maybe something else for its resampler). Even that seems [non-trivial](https://discourse.itk.org/t/find-all-available-modules-from-groupio/351/4)

**Comment by rijobro** [comment]
I've been trying this, but I've just realised that this will only compile the python version of ITK...

**Comment by rijobro** [comment]
#295 attempts to fix this.

**Comment by rijobro** [comment]
@KrisThielemans  any idea what to do with Travis at the moment? ITK successfully builds, stir links against it, but then the `PET_TESTS_PYTHON` fails with:
```
ImportError: No module named _pystir
```
Can't figure out how the two are related (but they are).

**Comment by KrisThielemans** [comment]
we're now having time-outs on Linux as well.

**Comment by casperdcl** [comment]
@rijobro I think that's #308. will have a look tomorrow.

**Comment by KrisThielemans** [comment]
weirdly, the Superbuild runs do not timeout, neither for Linux nor OSX, see e.g. [here](https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/builds/497923778). Probably some caching. I've asked Travis-ci for an extension of the run-time limit.

**Comment by KrisThielemans** [comment]
This was resolved by getting a 2 hour limit (and reducing build time with https://github.com/CCPPETMR/SIRF-SuperBuild/pull/211). So I'll close this.

Testing the conda stuff is probably for another issue (once the upstream problem has been resolved).
