### ISSUE TITLE
Python class definition uses old style

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF#291]
Since version 2.2 Python supports the so called [new style](https://wiki.python.org/moin/NewClassVsClassicClass) class definition which is the recommended way to create a class in modern Python.

SIRF Python classes are old style.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov is this very easy? Otherwise postpone.

**Comment by evgueni-ovtchinnikov** [comment]
fixed by 8273ee8f2573b4a629a923b949bd995dcba1ecea
