### ISSUE TITLE
Knowing if STIR has been built with ITK

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#294]
I have a synergistic test that tries to convert STIRImageData, NiftiImageData (and at some point in the future GadgetronImageData).

To do this, I require STIR to have been built with ITK. Currently, I build the synergistic code as follows:
```
if (REG_ENABLE AND STIR_REGISTRIES AND cGadgetron_LIBRARY_DIRS)
  ADD_SUBDIRECTORY(src/Synergistic)
endif()
```
However, it should be more like:
```
if (REG_ENABLE AND STIR_REGISTRIES AND cGadgetron_LIBRARY_DIRS AND STIR_BUILT_WITH_ITK)
  ADD_SUBDIRECTORY(src/Synergistic)
endif()
```
Any ideas how I can determine if STIR was built with ITK? Would I need to alter the `STIRConfig.cmake` file generated by STIR?

**Comment by rijobro** [comment]
As a temporary fix, I loop through all CMake variables just after the STIR `find_package`. Experimentally, I've noticed that there are ITK entries only if STIR was built with ITK. Therefore I loop over all cmake variables and if any contain the keyword 'ITK', I assume STIR was built with ITK. 

This doesn't seem very elegant, but it works for the cases I've tested...

**Comment by ashgillman** [comment]
You could set a specific variable (e.g., STIR_BUILT_WITH_IT) within STIR that can be used by upstream packages such as SIRF?

**Comment by rijobro** [comment]
Well setting it in the STIR CMake won't necessarily mean it would be available in SIRF, which is why I was thinking about adding it to the `STIRConfig.cmake` file, as the variables would be made available when you do `find_package(STIR)`. Thoughts?

**Comment by ashgillman** [comment]
Hmm, if ITK variables are being set by STIR there must be a way? I've just had a quick Google but didn't see much :/

**Comment by KrisThielemans** [comment]
Seems to me that this would be a useful thing to add in the `STIRConfig.cmake`. Also for the other optional packages then of course. Seems fairly easy to do (sit it to the value of `HAVE_ITK` or so). Please create a STIR PR

**Comment by rijobro** [comment]
Done: https://github.com/UCL/STIR/pull/307

**Comment by KrisThielemans** [comment]
will have to update SIRF-SuperBuild version_config once accepted.
