### ISSUE TITLE
Travis failing for linux

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#300]
Until ed219b4da022d4628df64d1f7769cd4c2c8a9e39, linux was green on Travis. Now they're red (https://travis-ci.org/CCPPETMR/SIRF/builds/488566474), but it's an FFTW error, so I don't think it's related to SIRF code changes. 

Any ideas as to what could be causing this? Could it be a knock-on effect from the Superbuild? (That said, the Superbuild is all green on Travis.)

**Comment by rijobro** [comment]
Due to https://github.com/CCPPETMR/SIRF-SuperBuild/commit/5b8cb8961a8db4376c67528abc98fc6442aad6b2

**Comment by KrisThielemans** [comment]
This was resolved by reverting the SuperBuild change
