### ISSUE TITLE
matlab: error catching in libload_*.m

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#302]
loading libraries in matlab currently looks like this:
```
    try
        [notfound, warnings] = loadlibrary('miutilities');
    catch
        error('mutilities library failed to load\n')
    end
```
However, the error message isn't very useful. If I remove the `try`/`catch`, I get a more informative message, e.g.:
```
Error using loadlibrary
There was an error loading the library
"/SAN/inm/tools/SIRF-Superbuild/Build/INSTALL/matlab/miutilities.mexa64"
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by
/SAN/inm/tools/SIRF-Superbuild/Build/INSTALL/matlab/miutilities.mexa64)

Caused by:
    Error using loaddefinedlibrary
    /lib64/libc.so.6: version `GLIBC_2.14' not found (required by
    /SAN/inm/tools/SIRF-Superbuild/Build/INSTALL/matlab/miutilities.mexa64)
```
And matlab doesn't crash (so seems safe (for my version at least)).

@evgueni-ovtchinnikov, @KrisThielemans: Would it be ok to remove the `try`/`catch`'s?

**Comment by KrisThielemans** [comment]
yes. let's remove `try/catch`. It will error out just like the current code, but at least we'll see why.
