### ISSUE TITLE
matlab alias

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#305]
With #297 we changed how libraries are loaded in Matlatb. 

Beforehand, when loading a library, we also returned a string. If the user did `eval(string)`, then the classes of the library could be used without the library name. E.g. (from `mSTIR/test_1.m`):
```
import_str = set_up_PET(engine);
eval(import_str)
...
image = ImageData();
```

This behaviour is no longer supported (and as such, matlab unit tests fail). Two solutions:
1. We can put the functionality back in by adding a second argument to `set_up_engine`. This argument is a bool, which if set to `true`, the eval is carried out inside the function (no need to return a string).
2. We don't support this behaviour.

I'm in favour of the second. It is equivalent to `from engine import *` in python and as per #265, we decided to avoid as much as possible. 

I would therefore suggest that we simply change all tests and examples that use `eval(import_str)` and everything should be fine. Thoughts?

**Comment by KrisThielemans** [comment]
I think we're possibly trying to do too much with 1 function. It might be better to split-off to functionality of the alias into a separate function, e.g. `set_up_engine_alias`. 

I had a look at the [MATLAB doc for import](https://www.mathworks.com/help/matlab/ref/import.html). It seems to me that we can now do
```matlab
set_up_PET;
i=mSTIR.ImageData(...);
% import one function into global namespace
import mSTIR.ImageData
i2=ImageData(...);
% import all classes into the global namespace (not recommended, but doable)
import mSTIR.*
i3=ImageData(...);
```
As you say, the `import` wouldn't work with an alias but it seems to me nobody would want to do that anyway (`pet=set_up_PET(); import pet.*` doesn't seem to make sense); Admittedly, it seems that currently the default choice used by `set_up_PET` isn't very useful anymore, as you need to know what the module is anyway, i.e. it makes more sense to type
```matlab
set_up_engine('STIR');
i=mSTIR.ImageData(...);
```
If we split-off the alias functionality, we can preserve backwards compatibility, although personally, I would have prefered to avoid the need for the user to type `eval`
```matlab
import_name = set_up_PET();
i1=mSTIR.ImageData(...);
import([import_name '.ImageData')
i2=ImageData(...);
```
I think this is cleaner than returning a string `import mSTIR.*` as that means users cannot only import `mSTIR.ImageData` (unless they start manipulating the string, which becomes a bit weird). However, as we're breaking backwards compatibility anyway, I find this too much trouble. Instead, I'd let `set_up_engine` print what the `import` statements should be.

So I suggest that 
- we drop the `eval()` functionality, 
- add a print statement about what to use for `import`
- add new functions such as `alias_as_struct= set_up_engine_alias('STIR')`

Clearly, this will need to be documented in `CHANGES.md` as a breaking change.

**Comment by KrisThielemans** [comment]
Aside from all this, I think we should have a `sirf` package for MATLAB as well. That would mean modifying the CMake `install` commands to put everything matlab related in `+sirf`, and of course all tests/demos to do stuff like
```matlab
sirf.set_up_engine('STIR');
i=sirf.STIR.ImageData(...);
```
Aside from the usual arguments about avoiding name conflicts, it has the advantage that it avoids people accidentally calling stuff in the source tree. (But that has the disadvantage that you can only run the tests after installing. That might already be the case for Python as well by the way, @casperdcl ?)

We could install both `+sirf/+STIR` and `+mSTIR` I guess, but I'd rather not.

**Comment by casperdcl** [comment]
> It is equivalent to `from engine import *` in python and as per #265, we decided to avoid as much as possible.

Not sure whether this should apply to MATLAB. Python users expect clearly defined imports (so no `import *`) but MATLAB users tend to like importing everything.

> But that has the disadvantage that you can only run the tests after installing. That might already be the case for Python as well by the way

Well since we're using swig to generate wrappers for py/mlab it makes sense that at least an in-place build (if not install) is required for tests (https://github.com/CCPPETMR/SIRF/pull/318#issuecomment-471456407).

**Comment by KrisThielemans** [comment]
> MATLAB users tend to like importing everything.

well, I'm not going to do a straw-poll among MATLAB users, but MATLAB strongly discourages `import package.*`.

> since we're using swig to generate wrappers for py/mlab it makes sense that at least an in-place build (if not install) is required for tests

Not sure what swig has to do with this (we're still not using it for Matlab by the way), but of course, the code has to be built before we can test the python/matlab and C++ routines. C++ can be tested after build (without install). The question is if we want to same for python/matlab. I think Matlab could be done by just moving directories like `xSTIR/mSTIR/+mSTIR` to `xSTIR/mSTIR/+sirf/+STIR` (and then having a lot of fun lines about running matlab with the correct paths). I'm not sure about Python.

In any case, it seems to me quite logical/uniform that in SIRF 2.0, we require a `sirf` namespace for C++/Matlab/Python, breaking backwards compatibility. Doing "build-only" testing is icing on the cake that we can do in SIRF 2.1.

**Comment by rijobro** [comment]
Personally, I would want to discourage users from doing `import mSTIR.*` or even `import mSTIR.ImageData`, since this then blocks us from using multiple engines (e.g., is `ImageData` from STIR, Gadgetron or NiftyReg?). 

To that end, I would be in favour of breaking backwards compatilibility. No need for `import` and no need for `eval`. If they <b>really</b> wanted to, people could still do `import mSTIR.ImageData` whether we give them the string or not.

However, if you disagree (and it sounds like you do), I'm happy to do it your way.

**Comment by rijobro** [comment]
After discussion with @KrisThielemans, we decided that the current implementation is OK (since it discourages `import mSTIR` etc.).

We have therefore simply to move `+mSTIR` to `+sirf/+STIR` (and similar for other packages).

**Comment by KrisThielemans** [comment]
and change all the demos and tests to have the `import` statements, and change `set_up_engine` to use the new names, and updated CHANGES, and update SIRF-exercises... sigh

By the way, `set_up_engine` still tries to catch some exceptions which has caused problems in the past. Possibly take the opportunity to remove these.

**Comment by rijobro** [comment]
PR #323 addresses this issue.

**Comment by rijobro** [comment]
Unless I'm mistaken, no changes are needed to SIRF-Exercises, as they are all python-based.
