### ISSUE TITLE
Fail to run reconstruct_from_listmode

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF#333]
@ckolbPTB reported by email the following issue.

I tried to run the demo "reconstruct_from_listmode" and I received the following error: 

```
File: /home/sirf/devel/build/INSTALL/python/sirf/STIR.py 
Line: 1666 
check_status found the following message sent from the engine: 
'DataSymmetriesForBins_PET_CartesianGrid can currently only support z-grid spacing equal to the ring spacing of the scanner divided by an integer. Sorry\n' exception caught at line 675 of /home/sirf/devel/build/sources/SIRF/src/xSTIR/cSTIR/cstir.cpp 
the reconstruction engine output may provide more information 
```

**Comment by paskino** [comment]
On the yet-to-release Ubuntu18.04 VM the code runs without issue.

**Comment by rijobro** [comment]
duplicate from #330.

**Comment by paskino** [comment]
How come it's duplicate? I don't see the error. What versions are you running.

**Comment by rijobro** [comment]
No, just that Christoph already created the issue, so we should be using that thread instead.
