### ISSUE TITLE
remove c-style casts

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#336]
Issue #330 arose from a missing `*` during a c-style cast. If we used `dynamic_cast` we would be less likely to make this problem. There is [at least one line](https://github.com/CCPPETMR/SIRF/blob/f8869bf05075767a1ad50c9e22a6154c3792930f/src/xSTIR/cSTIR/stir_data_containers.cpp#L29) that definitely needs to be changed, but there may be others. (Note that the macro is called `DYNAMIC_CAST`, but it is actually c-style.)

**Comment by KrisThielemans** [comment]
And switching the macro over to `dynamic_cast` created trouble with `const`. That is a sign of trouble as well.

This might have to be a 2.1 issue

**Comment by rijobro** [comment]
Can we not have:
```
#define DYNAMIC_CAST...
#define DYNAMIC_CAST_CONST...
```
The compiler wil tell you pretty quickly which ones you should be using.

**Comment by KrisThielemans** [comment]
The fact that using `dynamic_cast` in the macro breaks some of the code means that the current C-style cast was also casting `const` away. Should be avoided as much as possible. If we need it, we need a `const_cast`.

I can see no good reason to introduce a macro for `dynamic_cast`. Much better to do it explicitly. C++11 isn't too bad for this
```c++
auto a = dynamic_cast<const WhatEverType&>(b);
```
is virtually the same to what we have now.

**Comment by evgueni-ovtchinnikov** [comment]
terribly sorry - forgot to change the definition of macro!
