### ISSUE TITLE
update doc for v2.0

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#341]
this needs changes to the UsersGuide, CHANGES.md (which seems quite incomplete), and potentially the DevelopersGuide.

**Comment by KrisThielemans** [comment]
somewhat duplicate of #246

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov I guess this can be closed?

**Comment by evgueni-ovtchinnikov** [comment]
still too little said about the registration stuff in user and developer guides i believe

**Comment by rijobro** [comment]
This can be closed from my point of view. @evgueni-ovtchinnikov just needs a bit more from your side for rc2 in `CHANGES.md`.

**Comment by KrisThielemans** [comment]
close?

**Comment by rijobro** [comment]
For me it can be closed. @evgueni-ovtchinnikov ?
