### ISSUE TITLE
segfault when creating pSTIR.AcquisitionData from scanner

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#349]
This crashes for me
```
import sirf.STIR
template_acq_data = sirf.STIR.AcquisitionData('Siemens_mMR')
```
Debugging shows that `ptr_t` at
https://github.com/CCPPETMR/SIRF/blob/8242f02392582e5201f04893102d230b3a19c20a/src/xSTIR/cSTIR/cstir.cpp#L536
is zero.

Any ideas?

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov the problem was that `_template` here
https://github.com/CCPPETMR/SIRF/blob/8242f02392582e5201f04893102d230b3a19c20a/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h#L180
was 0. @rijobro and I didn't understand it and have replaced it with `PETAcquisitionDataInMemory` (which seems correct: you don't have a filename) in #349. However, feel free to improve on that. In any case, there seems to be no guarantee that `_template` is initialised, so this feels very unsafe.

**Comment by KrisThielemans** [comment]
This must have been because I didn't first call
```python
sirf.STIR.AcquisitionData.set_storage_scheme(storage)
```
Clearly, we need to have a default storage scheme. My feeling is that this should really be implemented using a singleton pattern (which isn't easy to do). Essentially: we need to have one plac where both initialisation and access  as managed. Minimum thing to do seems to merge `init` code into `storage_template` 
```C++
static stir::shared_ptr<PETAcquisitionData> storage_template()
{
  if (!_template)
   {
     PETAcquisitionDataInFile::set_as_template();
   }
   return _template;
}
```
replace all access to `_template->` to `storage_template()->` and remove calls to `init` everywhere. It still isn't ideal as `PETAcquisitionDataInFile` and derived classes still have access to `_template` (and need it because of `set_as_template`) but I guess we can resolve that by some local documentation. 

I don't think this is 100% safe though. Access to static variables is always dangerous as you don't know in which order they get initialised (AFAIK it's only safe if the `_template` variable would be a static member of `storage_scheme`, but then we cannot set). Alternatively, we spin off the `storage_scheme` stuff into a separate class which would be a true singleton. We can leave that for later.

**Comment by evgueni-ovtchinnikov** [comment]
default storage scheme is 'file'
sorry for the bug, will fix it properly today

**Comment by KrisThielemans** [comment]
not sure about https://github.com/CCPPETMR/SIRF/commit/af279632163ce8b0028939ae5b79ad02e0880bc9. I think it creates a `ProjDataInMemory` and then throws it away. Can be just 1GB for nothing. Also, it doesn't add a check on `_template` so this bug could happen somewhere else.

Reopen and reassign to 2.1?

**Comment by evgueni-ovtchinnikov** [comment]
sorry, made a silly quick fix (mistook `same_acquisition_data` for `new_acquisition_data`)

a new fix pushed (if not good enough, let us reassign to 2.1)
