### ISSUE TITLE
petmr_data_path returns capitalised directory

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF#358]
```python
import pSTIR as pet
pet.petmr_data_path('mMR')
Out[11]: '/home/sirfuser/devel/buildVM/sources/SIRF/data/examples/MMR'
```

The directory is not correct.

**Comment by rijobro** [comment]
From `Utilities.py`, the code is:
```
data_path = '/data/examples/' + petmr.upper()
```
So you can see that it will just add whatever you give it to the examples path. You should give 'PET' as the input argument, and then add the 'mMR' manually.

**Comment by KrisThielemans** [comment]
please use `example_data_path` anyway (see #339)
