### ISSUE TITLE
Prepare for PET TOF support

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#359]
Create a “dummy” TOF dimension (just setting num of TOF bins to 1).

Modifications:

- [ ] `cstir.cpp`: `cSTIR_getAcquisitionsDimensions(const void* ptr_acq, size_t ptr_dim)`

- [ ] `STIR.py`: PETAcquisitionData L725 and onwards:
    -	`dimensions `
    -	`as_array` (call `dimensions()` as opposed to repeating code)

- [ ] similar mods for MATLAB

- [ ] Changes to tests/demos to cope with extra dimension

**Comment by KrisThielemans** [comment]
@eliseemond @NikEfth could you confirm that STIR projdata 'fill' etc has TOF dimension as "slowest running" (i.e. TOF, segment, axialpos, view, tangpos)

**Comment by NikEfth** [comment]
It does [line](https://github.com/NikEfth/STIR/blob/ad906823bbc111bc59865436e10a4e2e17059abc/src/buildblock/ProjData.cxx#L388)
