### ISSUE TITLE
check checklist

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#376]
- I think some items related to the VM can be removed from our checklist.
- Let's add running and tagging SIRF-exercises to the checklist

**Comment by KrisThielemans** [comment]
@paskino, is "deselect the serial port." still necessary?

Please add SIRF-exercises.

**Comment by KrisThielemans** [comment]
Also @casperdcl's recommendation: add

- create release on https://github.com/CCPPETMR/SIRF/releases/new linked to the tag and copying all CHANGES.md since last release

**Comment by casperdcl** [comment]
to be explicit this should include everything since the last release as listed on https://github.com/CCPPETMR/SIRF/releases (so all the release candidates/tags since v1.1.0)

**Comment by paskino** [comment]
"deselect serial port" isn't necessary, but worth keeping and checking.

**Comment by KrisThielemans** [comment]
running SIRF-exercises checklist should mention download data.

**Comment by rijobro** [comment]
and then delete data once finished?

**Comment by KrisThielemans** [comment]
No, as the checklists says, the VM needs to be exported before running any tests, as we don't clean up afterwards.

**Comment by KrisThielemans** [comment]
the SIRF-exercises checks need to happen before upload obviously. The check list items therefore need to be re-ordered

**Comment by KrisThielemans** [comment]
"email" should specify all email lists to use
