### ISSUE TITLE
need to check type of arguments of functions

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#38]
in Python (and probably in MATLAB) we can get confusing error messages like this
```
acq_model.set_additive_term('ADDSINO_g1.hs');
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kris/python/pStir.py", line 657, in set_additive_term
    (self.handle, 'AcquisitionModel', 'additive_term', at.handle)
AttributeError: 'str' object has no attribute 'handle'
```
The reason is that `set_additive_term` expects an `AcquisitionData` object, which has a `handle`, but we pass a string.

Also, when can apparently pass the wrong type of object without any error message at all,  e.g.
```
acq_model.set_additive_term(image)
```
does not complain. Doing the forward projection then just hangs or causes seg faults as the Image handle will be interpreted as an `AcquisionData` handle.

**Comment by evgueni-ovtchinnikov** [comment]
Checking all arguments of all functions is quite a job. Are you sure it is a priority right now?

**Comment by KrisThielemans** [comment]
no sure. no priority now! milestone 0.9.1 :-)

**Comment by KrisThielemans** [comment]
check boost::any

**Comment by evgueni-ovtchinnikov** [comment]
done on devel
