### ISSUE TITLE
pStir.AcquisitionModel.set_background_term is ignored in objective function

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#39]
the background term is only handled in `forward`, but the objective function only looks at the additive term (L283 in stir_x.h).

We need to handle this correctly, or at least throw an error ("Use of a background term is currently still unsupported. Use an additive term instead.")

**Comment by evgueni-ovtchinnikov** [comment]
So far as I can see, STIR does not do background term.

I suggest we simply comment out set_background_term() for now rather than make it throw an error.

**Comment by KrisThielemans** [comment]
I'm fine with commenting it out but it's not trivial. Python, MATLAB, User's Guide. Throwing an error is in one place?

**Comment by evgueni-ovtchinnikov** [comment]
Commenting out/removing from User’s guide does not require any testing, and so will be easier.

Besides, having in User’s Guide something that does not really work would be confusing and not user-friendly - the user will only discover that their script cannot possibly work after they have written it.

**Comment by KrisThielemans** [comment]
sure. up to you.

**Comment by evgueni-ovtchinnikov** [comment]
set_background_term() commented out and removed from User's Guide

**Comment by evgueni-ovtchinnikov** [comment]
commented out for now, eventually needs to be implemented in STIR and interfaced to SIRF

**Comment by KrisThielemans** [comment]
can be done in SIRF as well by doing algebraic manipulations.
reopening for v1.0 such that don't forget

**Comment by evgueni-ovtchinnikov** [comment]
done on devel
