### ISSUE TITLE
create release for SIRF_data?

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#402]

**Comment by KrisThielemans** [comment]
we currently don't tag SIRF_data. Cleaner to do it, and would allow having fixed URLs.
If we do this, we'd have to add it to our checklist

**Comment by casperdcl** [comment]
should also squash all changes since last tag into one commit

**Comment by KrisThielemans** [comment]
why squash? I'm even more scared of that with subrepos than with the normal repo...

**Comment by casperdcl** [comment]
squash to avoid the intermediate (possibly deleted) data increasing repository size

**Comment by KrisThielemans** [comment]
I don't want to make a squash part of the regular release scheme. If this kind of thing happens, then it should be handled there-and-then.

In any case, the commits on SIRF_data since SIRF 2.0.0 (i.e. since https://github.com/CCPPETMR/SIRF_data/tree/cd139a1c69fafb0b2126495d8716c0ee3e38c9dd) were all quite beautiful (and mine!).

**Comment by KrisThielemans** [comment]
I've tagged https://github.com/CCPPETMR/SIRF_data/tree/cd139a1c69fafb0b2126495d8716c0ee3e38c9dd:
https://github.com/CCPPETMR/SIRF_data/tree/v2.0.0

**Comment by KrisThielemans** [comment]
@casperdcl feel like doing a PR for the checklist or telling me (again) how to make sure that the `data` submodule is really what it should be. I'm afraid that just saying
```
cd data
git tag -a v$VER -m "version $VER"
```
isn't safe enough

**Comment by casperdcl** [comment]
yes, after that you need:

```bash
git push --tags
cd ..
git add data/
git commit -m "update data submodule to $VER"
```

**Comment by casperdcl** [comment]
@KrisThielemans not sure which checklist you want a PR on. https://github.com/CCPPETMR/SIRF/blob/master/CONTRIBUTING.md#submodules has instructions.

**Comment by KrisThielemans** [comment]
I think the following only needed if any changes are made (i.e. not related to tagging/release)
```
git add data/
git commit -m "update data submodule to $VER"
```
These instructions are indeed in the `CONTRIBUTING` which is where they should be I think.

In fact, from that doc, I think we need
```
git submodule update
```
before my lines?

I was talking about https://github.com/CCPPETMR/SIRF/blob/master/doc/ReleaseChecklist.md

**Comment by casperdcl** [comment]
I wouldn't `git submidule update` as that would leave the submodule checkout out at a commit rather than on a branch. I would instead add `cd data && git checkout master && git pull`.

**Comment by KrisThielemans** [comment]
hmmm. Who knows if `master` will be the correct commit? Again, I believe that having the correct `data` submodule added to the SIRF repo should have been managed before the release check-list process.

We could add a warning for the "checklister" about the above and recommend to do `git checkout master&git pull` after the release?

**Comment by casperdcl** [comment]
ah we're talking at cross-purposes. there are 2 scenarios:

1. checklister knows nothing of development and is only creating a release, in which case *should never `git commit` anything* (only `git submodule update` and `git tag`)
2. checklister is a dev who may have modified `data` checked out etc in which case they need to `checkout master` and `commit`

**Comment by casperdcl** [comment]
moved discussion to #456
