### ISSUE TITLE
Travis fails building PRs from other forks

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#410]
Branches from my fork of SIRF that I want to PR into master fail with the following error:

```
Cloning into 'SIRF'...
Note: checking out 'e66070e1a3e6f8a00dd515dc7b43177207a58301'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

fatal: reference is not a tree: 7c3e5ea1fd3e19bba75c0b8ac905da02b80a91ae
CMake Error at /home/travis/build/CCPPETMR/SIRF-SuperBuild/builds/SIRF/tmp/SIRF-gitclone.cmake:75 (message):
  Failed to checkout tag: '7c3e5ea1fd3e19bba75c0b8ac905da02b80a91ae'
```

Until now I've simply pushed to the CCPPETMR branch, but this isn't possible for everyone (nor is it a long-term solution).

**Comment by casperdcl** [comment]
pretty sure this is a duplicate issue (maybe from superbuild).

Can't fix as it's a travis security feature.

However the error message you posted doesn't look like what I expected.

**Comment by rijobro** [comment]
Couldn't see a similar issue in either this or the superbuild repos. I've mentioned this problem orally before, perhaps that's what you're thinking of? (Or i missed a similar issue, which is completely possible.)

This seems like a fairly serious problem then. It means that anyone who doesn't have write access to branches in the CCPPETMR repo can create a PR to our main branch, but we have no way of knowing if it builds successfully or not.

**Comment by rijobro** [comment]
@casperdcl just looking at this again. Is there anyway we can fix it?

Maybe modifying the following?

https://github.com/CCPPETMR/SIRF/blob/d38d06321f37d0428cd2bee613c1279f417439bd/.travis.yml#L227-L230

E.g., (just an idea) changing `-DSIRF_URL` from `$PWD` to `www.github.com/${TRAVIS_PULL_REQUEST_SLUG}`?

where:

> TRAVIS_PULL_REQUEST_SLUG:
> - if the current job is a pull request, the slug (in the form owner_name/repo_name) of the repository from which the PR originated.
> - if the current job is a push build, this variable is empty ("").

Obviously if string is empty we do the same as before.

**Comment by casperdcl** [comment]
ah I just realised you mean *all* builds fail. Sure, we should be able to fix it so tests at least run.

**Comment by casperdcl** [comment]
it's just uploading etc which shouldn't work

**Comment by rijobro** [comment]
So should I try my suggestion? Happy to leave it for you if you have a better idea.

**Comment by casperdcl** [comment]
I'll take a look later today. There are probably a couple of other things which need changing.

**Comment by casperdcl** [comment]
@rijobro in https://github.com/CCPPETMR/SIRF/issues/406#issuecomment-507700260 you state #409 had an issue because of this (#410), but it seems https://travis-ci.org/CCPPETMR/SIRF/jobs/553260831 ran just fine. What's the issue?

**Comment by casperdcl** [comment]
Aha I think I've found https://travis-ci.org/CCPPETMR/SIRF/jobs/591111066#L19909

Much idiotic such fun. here haz PR:

**Comment by casperdcl** [comment]
Restarted https://travis-ci.org/CCPPETMR/SIRF/builds/591111065 after merge - @rijobro please reopen if it fails again due to the same issue

**Comment by rijobro** [comment]
Bad news, https://travis-ci.org/CCPPETMR/SIRF/builds/591111065 failed

**Comment by casperdcl** [comment]
interesting - it's because it didn't re-build against the new master. I think the related PR (#449) will have to be pushed to again to force it to build against the new master.

**Comment by rijobro** [comment]
Ok, I'll let you know for the next PR that I push from my fork.

**Comment by casperdcl** [comment]
nope still failing.

https://travis-ci.org/CCPPETMR/SIRF/jobs/591412957#L1679 yet https://travis-ci.org/CCPPETMR/SIRF/jobs/591412957#L18934:

```bash
$ git symbolic-ref -q HEAD || git checkout -b local_$TRAVIS_COMMIT
Switched to a new branch 'local_d063ccde407f2740eebc704b39eb2c730e727e46'
[...]
Cloning into 'SIRF'...
[...]
fatal: reference is not a tree: d063ccde407f2740eebc704b39eb2c730e727e46

CMake Error at /home/travis/build/CCPPETMR/SIRF-SuperBuild/builds/SIRF/tmp/SIRF-gitclone.cmake:75 (message):

  Failed to checkout tag: 'd063ccde407f2740eebc704b39eb2c730e727e46'
```

Are we sure `-DSIRF_URL=$PWD` is being honoured? Perhaps this is an issue with `ExternalProject`?

**Comment by casperdcl** [comment]
looks to be the same as https://github.com/intel/caffe/issues/183

**Comment by rijobro** [comment]
I've used `SIRF_URL` plenty of times and never had a problem, so I would say that yes, it's being honoured. Perhaps if `$PWD` returns something unexpected (neither a URL nor source repository), it doesn't do anything (similar to our recent PR https://github.com/CCPPETMR/SIRF-SuperBuild/pull/265, in which we set `GIT_URL` to `""` if we don't want it to perform the checkout)?

**Comment by casperdcl** [comment]
The problem is I could replicate the original issue on my machine but adding `git checkout -b local_$TRAVIS_COMMIT` fixed it, which means `-DSIRF_URL=$PWD` (and everything else) seems to work on my machine. It's just failing on travis. Making this hard to debug.

**Comment by KrisThielemans** [comment]
could use our new facility of interactive debugging in Travis... (if that'd help)

**Comment by rijobro** [comment]
As per [this PR](https://travis-ci.org/CCPPETMR/SIRF/builds/645919419?utm_source=github_status&utm_medium=notification) on my fork, OSX jobs give the following error:
```
fatal: reference is not a tree: ec87ff4183b7d938bdb9513bca570d18c9502a99
CMake Error at /Users/travis/build/CCPPETMR/SIRF-SuperBuild/builds/SIRF/tmp/SIRF-gitclone.cmake:40 (message):
    Failed to checkout tag: 'ec87ff4183b7d938bdb9513bca570d18c9502a99'
```

**Comment by evgueni-ovtchinnikov** [comment]
same with my OSX builds

**Comment by rijobro** [comment]
With branches on your fork or the CCPPETMR fork? If its the latter, then it seems like a pure OSX Travis problem (not related to branches on different forks).

**Comment by evgueni-ovtchinnikov** [comment]
PR from CCPPETMR/SIRF branch fix-acq-sort (push went ok)

**Comment by rijobro** [comment]
ok, opening a new issue (https://github.com/CCPPETMR/SIRF/issues/539) and closing this one instead.
