### ISSUE TITLE
Use consistent naming for mGadgetron, mgadgetron, cgt CMake library etc

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#43]
Currently capital G, S and U are used for interface folders and modules (e.g. pStir), and smallcase for interface libraries (pystir). However, we have cgt (should be cgadgetron) and iutil (should be iutilities)

Devise a consistent naming scheme (and document it)

**Comment by evgueni-ovtchinnikov** [comment]
Done on devel.
