### ISSUE TITLE
Problems with SuperBuild on Mac

### ISSUE THREAD

**Issue by mehrhardt** [CCPPETMR/SIRF#435]
I am trying to install SIRF on my mac with medium success. Any help is greatly appreciated!
 
**First**, the installation instructions on https://github.com/CCPPETMR/SIRF/wiki/SIRF-SuperBuild-on-MacOS are outdated by now. **Homebrew** does not allow for options anymore, such that
 
                brew install hdf5 --enable-cxx
 
is not supported. However, in this case hdf5 has “—enable-cxx” as a default option now so this is not a problem.
 
**Second**, and more importantly, I have trouble with the installation of **Gadgetron**. I try to install the SuperBuild via
 
                cmake ../..
                make
 
which resulted in
 
CMake Error at SuperBuild/External_Gadgetron.cmake:60 (message):
  Gadgetron needs CBLAS_LIBRARY and CBLAS_INCLUDE_DIR.  If
 
        these variables do not exist in your CMake, create them manually. CBLAS_LIBRARY
        and CBLAS_INCLUDE_DIR should be FILEPATH and PATH, respectively, and live in
        /usr/local/Cellar/openblas/ if installed with "brew install openblas".
Call Stack (most recent call first):
  CMake/ExternalProjectDependency.cmake:593 (include)
  CMake/ExternalProjectDependency.cmake:639 (ExternalProject_Include_Dependencies)
  SuperBuild.cmake:227 (ExternalProject_Include_Dependencies)
  CMakeLists.txt:17 (include)
 
Following these instructions, I tried
 
cmake ../.. -DCBLAS_LIBRARY="/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Versions/Current" -DCBLAS_INCLUDE_DIR="/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers"
make
 
and
 
cmake ../.. -DCBLAS_LIBRARY="/usr/local/Cellar/openblas/0.3.7/lib" -DCBLAS_INCLUDE_DIR="/usr/local/Cellar/openblas/0.3.7/include"
make
 
which both lead to
 
[  6%] Linking CXX shared library libgadgetron_toolbox_cpufft.dylib
[  7%] Built target gadgetron_toolbox_cpufft
[  7%] Linking CXX shared library libgadgetron_toolbox_cpuklt.dylib
Undefined symbols for architecture x86_64:
  "_wrapper2_cgesdd_", referenced from:
      bool arma::auxlib::svd_dc_econ<float, arma::Mat<std::__1::complex<float> > >(arma::Mat<std::__1::complex<float> >&, arma::Col<float>&, arma::Mat<std::__1::complex<float> >&, arma::Base<std::__1::complex<float>, arma::Mat<std::__1::complex<float> > > const&) in hoNDKLT.cpp.o
  "_wrapper2_cgesvd_", referenced from:
      bool arma::auxlib::svd_econ<float, arma::Mat<std::__1::complex<float> > >(arma::Mat<std::__1::complex<float> >&, arma::Col<float>&, arma::Mat<std::__1::complex<float> >&, arma::Base<std::__1::complex<float>, arma::Mat<std::__1::complex<float> > > const&, char) in hoNDKLT.cpp.o
  "_wrapper2_dgesdd_", referenced from:
      bool arma::auxlib::svd_dc_econ<double, arma::Mat<double> >(arma::Mat<double>&, arma::Col<double>&, arma::Mat<double>&, arma::Base<double, arma::Mat<double> > const&) in hoNDKLT.cpp.o
  "_wrapper2_dgesvd_", referenced from:
      bool arma::auxlib::svd_econ<double, arma::Mat<double> >(arma::Mat<double>&, arma::Col<double>&, arma::Mat<double>&, arma::Base<double, arma::Mat<double> > const&, char) in hoNDKLT.cpp.o
  "_wrapper2_sgesdd_", referenced from:
      bool arma::auxlib::svd_dc_econ<float, arma::Mat<float> >(arma::Mat<float>&, arma::Col<float>&, arma::Mat<float>&, arma::Base<float, arma::Mat<float> > const&) in hoNDKLT.cpp.o
  "_wrapper2_sgesvd_", referenced from:
      bool arma::auxlib::svd_econ<float, arma::Mat<float> >(arma::Mat<float>&, arma::Col<float>&, arma::Mat<float>&, arma::Base<float, arma::Mat<float> > const&, char) in hoNDKLT.cpp.o
  "_wrapper2_zgesdd_", referenced from:
      bool arma::auxlib::svd_dc_econ<double, arma::Mat<std::__1::complex<double> > >(arma::Mat<std::__1::complex<double> >&, arma::Col<double>&, arma::Mat<std::__1::complex<double> >&, arma::Base<std::__1::complex<double>, arma::Mat<std::__1::complex<double> > > const&) in hoNDKLT.cpp.o
  "_wrapper2_zgesvd_", referenced from:
      bool arma::auxlib::svd_econ<double, arma::Mat<std::__1::complex<double> > >(arma::Mat<std::__1::complex<double> >&, arma::Col<double>&, arma::Mat<std::__1::complex<double> >&, arma::Base<std::__1::complex<double>, arma::Mat<std::__1::complex<double> > > const&, char) in hoNDKLT.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [toolboxes/klt/cpu/libgadgetron_toolbox_cpuklt.3.17.0.dylib] Error 1
make[4]: *** [toolboxes/klt/cpu/CMakeFiles/gadgetron_toolbox_cpuklt.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [builds/Gadgetron/stamp/Gadgetron-build] Error 2
make[1]: *** [CMakeFiles/Gadgetron.dir/all] Error 2
make: *** [all] Error 2
 
Many thanks for your help!
Matthias

**Comment by mehrhardt** [comment]
Thanks to @rijobro for some tips on how to build Gadgetron on a mac. Based on his comments I was finally able build it using
`cmake ../.. -DUSE_SYSTEM_ACE=ON -DUSE_SYSTEM_Armadillo=ON -DUSE_SYSTEM_Boost=ON -DUSE_SYSTEM_HDF5=ON -DUSE_SYSTEM_SWIG=ON -DUSE_SYSTEM_siemens_to_ismrmrd=OFF -DCBLAS_LIBRARY="/usr/local/Cellar/openblas/0.3.7/lib/libopenblasp-r0.3.7.dylib" -DCBLAS_INCLUDE_DIR="/usr/local/Cellar/openblas/0.3.7/include"`

**Comment by KrisThielemans** [comment]
excellent. can someone update the wiki accordingly?
