### ISSUE TITLE
pet_data_path.m et al. need to use a global variable

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#44]
`pet_data_path` checks for `SIRF_PET_DATA_PATH` but this will never work. If we want this, we would need
to add
```
global SIRF_PET_DATA_PATH
```
Its documentation will need to mention this global variable. 

Same issue for MR of course.

Note that the documentation for `pet_data_path` currently says it's the MR data path.

**Comment by evgueni-ovtchinnikov** [comment]
These two scripts (pet_data_path.m and mr_data_path.m) simply allow the user to redefine demos’ input data path by setting a Matlab variable.

An explanation is added to both.

By the way, do we need copyright statements for such small and trivial scripts?
