### ISSUE TITLE
Minimisation or Maximisation for STIR ObjectiveFunction

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF#442]
Currently the CIL algorithms will try to minimise an objective function. 

However, in STIR, the equivalent is done by maximising the objective function, thought as likelihood.

This fundamental difference makes it difficult to use STIR `ObjectiveFunction` in CIL algorithms. Additionally also in the MRI and optimisation communities algorithms are used to minimise rather than maximise. 

A solution to this would be to have SIRF return the negative likelihood, and negative gradient, as CIL, leaving STIR handle it as is.

**Comment by paskino** [comment]
For the value just a `-` sign at [this](https://github.com/CCPPETMR/SIRF/blob/master/src/xSTIR/cSTIR/cstir.cpp#L745) line would do.

For the `cSTIR_objectiveFunctionGradient`, would it be possible to add a `grad *= -1` at [this](https://github.com/CCPPETMR/SIRF/blob/master/src/xSTIR/cSTIR/cstir.cpp#L789) line?

Similar for `cSTIR_objectiveFunctionGradientNotDivided`

**Comment by evgueni-ovtchinnikov** [comment]
I am not sure it would be a good idea to change the sign of objective function value and gradient in SIRF PET: so far as I can see, PET people think in terms of Expectation Maximization (many PET algorithms have EM in their names), and may be confused. I would have min/max switch in CIL objects, or else instruct the user to apply CIL algorithms to `-obj_fun` (c.f. `steepest_ascent.py` demo, which maximizes the objective function using minimization function `scipy.optimize.fminbound`).

**Comment by KrisThielemans** [comment]
I now think this indeed could be confusing and any case a fair amount of work. for instance, we would of course have to change the name from `...Poissonloglikelihood...` to something else (as it'd be minus the log-likelihood).

what about make a Python class like `ChangeSign` that takes an objective function class, and just the sign of the `get_value`, `__call__` and `gradient` (which I guess you guys have somewhere already with a hack), but forwards other class members?

**Comment by paskino** [comment]
I think we found out that the sign is correct, and it's just the gradient that must be inverted.

I'd agree to create a `ChangeSign` class to wrap the objective function and achieve our goal.

**Comment by KrisThielemans** [comment]
it's quite unlikely that the gradient and value are inconsistent. STIR tries to be consistent about this, but who knows. The demo for OSEM shows that objective function values increase, as they should. @evgueni-ovtchinnikov could have noticed if the gradient has the opposite sign when doing the gradient ascent.

**Comment by KrisThielemans** [comment]
@paskino @epapoutsellis I think this `ChangeSign` class should sit in CIL. It would be useful for anyone who wants to use CIL for maximisation. Putting it there means that you know which member functions need changing the sign. What do you think?

**Comment by jakobsj** [comment]
More generally, we could introduce a `ScaledFunction`, similar to our `ScaledOperator`
https://github.com/vais-ral/CCPi-Framework/blob/15313a44f63389afdaa49b5379f89d1bfc064e07/Wrappers/Python/ccpi/optimisation/operators/ScaledOperator.py#L21
taking a scaling factor as input and with the sign change as the special case of a scaling factor of -1.

**Comment by jakobsj** [comment]
In fact, we've already got it!
https://github.com/vais-ral/CCPi-Framework/blob/master/Wrappers/Python/ccpi/optimisation/functions/ScaledFunction.py

**Comment by KrisThielemans** [comment]
:-)

**Comment by KrisThielemans** [comment]
I believe therefore that I can close this.
