### ISSUE TITLE
python fill should take C- and F-order numpy arrays into account

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#452]
On the registration side, I didn't take into account whether the input numpy array was C- or F-order, which led to problems for one of the two. I've just fixed this (44ce4729c40797422847a139c08cd2040ab1565b). 

I'm not 100% sure, but looking through the code for pSTIR (and therefore I would guess Gadgetron), these need to be taken into account. 

The code in `ImageData::fill` in `Reg.py` now looks like this:
```
if not v.flags['F_CONTIGUOUS']:
    v = numpy.asfortranarray(v)
```

This is because I need F-order array. But it looks like STIR needs C-Style numpy array, so the code would have to be modified accordingly.

To test visually (check for striding problems):
```
im = ImageData('some_image')
arr = im.as_array()
arr_C = numpy.ascontiguousarray(arr)
arr_F = numpy.asfortranarray(arr)
im.fill(arr_C)
im.write('temp_C')
im.fill(arr_F)
im.write('temp_F')
```
Presumably (but not tried yet) we could put it in the `ctest` with:
```
im = ImageData('some_image')
arr = im.as_array()
arr_C = numpy.ascontiguousarray(arr)
arr_F = numpy.asfortranarray(arr)
im.fill(arr_C)
arr_C2 = im.as_array()
im.fill(arr_F)
arr_F2 = im.as_array()
assert(np.array_equal(arr_C2, arr_F2))
```

Thoughts?

**Comment by rijobro** [comment]
Just confirmed the test here: 04e1afc.

**Comment by evgueni-ovtchinnikov** [comment]
i believe we should strive to make things as simple as possible for users, they cannot be expected to carefully read user's guides

python users would expect c-contiguous arrays - in fact, many would not even know/care what it means, happy with whatever default ndarray settings are

if your reg code requires f-contiguity, i believe it should take care about the conversion, preferably on c++ level

**Comment by rijobro** [comment]
I agree that we should hide C-/F-style arrays from the user. But if someone passes a F-order numpy array into `sirf.STIR.ImageData::fill` I think your current implementation will fall over.

**Comment by KrisThielemans** [comment]
So, all `as_array` functions should return C-order (default in numpy). all `fill` functions should first store original order, convert to C-order, at the end convert back to original
