### ISSUE TITLE
get_output() does not call set_up_geom_info()

### ISSUE THREAD

**Issue by ckolbPTB** [CCPPETMR/SIRF#527]
When using e.g. FullySampledReconstructor() to reconstruct and MR image and then call get_output() to get an Gadgetron.ImageData object, set_up_geom_info() is not called. It is only called when writing/reading to/from file. 

This means after calling get_output() and then doing Reg.NifitImageData3D(Gadgetron.ImageData) an error occurs.

**Comment by rijobro** [comment]
@evgueni-ovtchinnikov I tried fixing this. I think the problem is that, at the start of the reconstruction, we create an empty `GadgetronImagesVector`. At the end of the reconstruction, `set_meta_data`, but we need to deserialise, and then call `set_up_geom_info`. 

I thought something along the lines of:
```
void
GadgetronImageData::set_meta_data(const AcquisitionsInfo &acqs_info)
{
    acqs_info_ = acqs_info;
    const ISMRMRD::IsmrmrdHeader &input_header = acqs_info.get_IsmrmrdHeader();
    for (unsigned i=0; i<number(); ++i)
        this->image_wrap(i).head() = input_header;
    this->set_up_geom_info();
}
```
Except that `this->image_wrap(i).head()` is of type `ISMRMRD::ImageHeader`, whereas `acqs_info.get_IsmrmrdHeader()` returns a `ISMRMRD::IsmrmrdHeader`. Any ideas?

**Comment by evgueni-ovtchinnikov** [comment]
We just forgot to call `set_up_geom_info()` in `ImagesReconstructor::process()` and `ImageProcessoror::process()`.

**Comment by rijobro** [comment]
I added the following to the end of `ImagesReconstructor::process()`:
`std::dynamic_pointer_cast<GadgetronImagesVector>(sptr_images_)->print_header(0);`
and the read, slice and phase directions are all zero:
```
read_dir:               0 0 0 
phase_dir:              0 0 0 
slice_dir:              0 0 0 
```
This means that we can't call `set_up_geom_info()` as it can't get any directional information. Don't we need to copy read, phase, slice directions etc from the input data?

**Comment by evgueni-ovtchinnikov** [comment]
No, this is done by Gadgetron. Apparently, you were running one of our test scripts, which by default use data generated by `ismrmrd_cartesian_shepp_logan`, and these data does not set properly a lot of things it should set, in particular those direction vectors are zeros. If you set the input file to one of David's, e.g. `grappa2_1rep.h5`, you should see non-zero direction vectors.

(I have actually started writing my Shepp-Logan generator, but was distracted by other things.)
