### ISSUE TITLE
(Non-TOF) unlisting of PET data (single time frame).

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF#53]

**Comment by KrisThielemans** [comment]
Need to merge STIR branch on CCPPETMR. Otherwise should work ok.

still needs data for demo. @bathomas will make short lm dataset in data, and full dataset on Zenodo. demo will use short data and produce noisy sinograms, and document how to get larger datasets from zenodo.

**Comment by evgueni-ovtchinnikov** [comment]
I put short listmode data files into data/examples/PET, but demo script could not find .l-file, apparently because in the header file only the name of the .l-file was given. Is there a way to obtain the path to an Interfile from within so that the header file could add its path to the name of .l-file?

**Comment by KrisThielemans** [comment]
STIR should read the .l file with a relative path to where the header is. If it doesn't, it's a bug in STIR. Can you try to reproduce with a STIR utility (e.g. `list_lm_events`). If that fails, can you send me the header?

**Comment by evgueni-ovtchinnikov** [comment]
As a quick fix, demo script copies .l-file to script's folder.

**Comment by evgueni-ovtchinnikov** [comment]
I appears, the reason was that I used CCPPETMR/STIR (as our users are supposed to). On VM, where I use UCL/STIR, all seems well.

When are we going to update CCPPETMR/STIR to UCL/STIR?

**Comment by evgueni-ovtchinnikov** [comment]
My previous comment was wrong - I forgot that I applied quick fix of copying list.l to the script's folder. When I removed it, the file was not found, so the problem persists.

**Comment by KrisThielemans** [comment]
yes indeed. it's a bug. See https://github.com/UCL/STIR/issues/133 which contains a suggested solution. Can you have a look at that?

Feel free to merge UCL/STIR/master to CCPPETMR/STIR/master. Our users aren't really supposed to use CCPPETMR/STIR anymore.  The Superbuild currently fixes a tag on UCL/STIR. I guess ideally we would merge UCL/STIR up to that tag in the future to avoid confusion, but I'm hesitant to say we will always do that as it creates overhead.

**Comment by evgueni-ovtchinnikov** [comment]
does CListModeDataECAT8_32bit::listmode_filename contain the needed path?

**Comment by evgueni-ovtchinnikov** [comment]
fixed filepath bug on CCPPETMR/STIR (after merging UCL/STIR)

**Comment by KrisThielemans** [comment]
merged fixes to UCL/STIR:master (and back to CCPPETMR/STIR:master). In future, please put fixes on branches, not on master.

**Comment by KrisThielemans** [comment]
Let us know when this is ready for wider testing.

**Comment by evgueni-ovtchinnikov** [comment]
I believe ListmodeToSinograms (as specified in Kris' Leeds slides) is fully functional now.
