### ISSUE TITLE
OSMAPOSLReconstructor by default writes all sub-iterations to file

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#541]
Probably surprising, and I guess undocumented, behaviour: you'll get `reconstructed_image_*.*v` in your current working directory. I recommend switching that off. If people want output, they need to ask for it. (It's surprising, potentially wasteful, and might crash if you don't have write permission in the cwd).

**Comment by evgueni-ovtchinnikov** [comment]
So far as I can see, the only way to switch writing to file off is via `set_disable_output()`, is it not?

**Comment by evgueni-ovtchinnikov** [comment]
BTW, I find this rather confusing:
```
template <typename TargetT>
void
Reconstruction<TargetT>::
set_enable_output(bool _val)
{
    this->_disable_output = _val;
}
```

**Comment by rijobro** [comment]
I find the method name `set_enable/disable_output` misleading, as we don't necessarily want to disable **all** output, just the output of the update after each subiteration.

**Comment by evgueni-ovtchinnikov** [comment]
As I wrote, I could not find other ways of implementing what Kris wanted in SIRF without editing STIR.

I initially thought about `set_save_interval(0)`, but this would need interpreting zero save interval as disabling save in STIR, so it becomes STIR issue.
