### ISSUE TITLE
resampling complex images

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#550]
We want to be able to resample complex images with niftyreg. This can be achieved by splitting the real and imaginary parts and resampling them independently.

I was thinking about having a `is_complex()` method for all `ImageData`. If `true` (some MR images), the resampler splits the image, as desired. 

I can see four possibilities:

1. reference and floating are both real. easy.
2. reference and floating are both complex. split real and imaginary, resample, join result together as complex image.
3. reference is complex, floating is real. resample, fill result into real component of reference, set imaginary part to 0.
4. reference is real, floating is complex. Tricky. Extract the magnitude of the floating image and resample that? Or resample each of the floating components and return two images with metadata matching that of the reference image? That would be annoying as `get_output()` would need to return two images.

Any thoughts @ckolbPTB @johannesmayer ?

**Comment by ckolbPTB** [comment]
In my opinion only 1 and 2 are relevant. I don't know a case for MR images where you would need to have 3 and 4. I would throw an error if floating and reference are different.

**Comment by KrisThielemans** [comment]
case 4: MR to PET registration?

I'm possibly missing the difficulty, but the reference is used for the resampler geometric stuff I guess, so for all cases, I'd

1.for both ref/float, if it's complex, take abs (i.e. don't take abs if real-valued)
2. call niftyreg registration, and get it's deformation
3 resample (original) float using the deformation, preserving it's original data-type.

no?

**Comment by rijobro** [comment]
closed via https://github.com/CCPPETMR/SIRF/pull/558
