### ISSUE TITLE
NIFTYREG lacks Targets

### ISSUE THREAD

**Issue by AnderBiguri** [CCPPETMR/SIRF#566]
In the ideal world, NiftyReg would have a `NIFTYREGTargets.cmake `(much in the same way that STIR has `STIRTargets.cmake`). 

In the meantime, however, we still need to link against CUDART library if NiftyReg was built with it, thus this PR: https://github.com/CCPPETMR/SIRF/pull/565 .

**Comment by rijobro** [comment]
Not sure if we should close this one as commit 5fa3b03 only solves this as a workaround. That said, it's not really a problem with our own code base.
