### ISSUE TITLE
compilation of xSTIR fails with STIR master due to listmode changes

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#571]
https://github.com/UCL/STIR/pull/445 introduced a change in the listmode hierarchy, which causes
```
/home/travis/build/CCPPETMR/SIRF-SuperBuild/sources/SIRF/src/xSTIR/cSTIR/stir_x.cpp: In member function â€˜float sirf::ListmodeToSinograms::get_time_at_which_prompt_rate_exceeds_threshold(float) constâ€™:
/home/travis/build/CCPPETMR/SIRF-SuperBuild/sources/SIRF/src/xSTIR/cSTIR/stir_x.cpp:38:16: error: â€˜CListModeDataâ€™ was not declared in this scope
     shared_ptr<CListModeData> lm_data_ptr
```

**Comment by KrisThielemans** [comment]
Cause:  `ListmodeToSinograms` is derived from `LmToProjData` which now has a ` shared_ptr<ListModeData> lm_data_ptr` (as opposed to `shared_ptr<CListModeData>`). Therefore, its `get_empty_record_sptr()` returns a `shared_ptr <ListRecord>` as opposed to a `shared_ptr <CListRecord>`.

I tried to put in an extra constructor:
```C++
class CListRecord : public ListRecord
{
public:
  CListRecord()
    {}
  CListRecord(const ListRecord& r) : ListRecord(r)
    {
    if (dynamic_cast<const CListRecord *>(&r) == 0)
      error("CListRecord constructor called with ListRecord of wrong type");
    }
};
```
But the error remains the same. Presumably this new constructor doesn't get called when it's wrapped in a `shared_ptr`.

I therefore currently see no other solution than @rijobro 's #574.

@danieldeidda any other ideas?

**Comment by danieldeidda** [comment]
Mh I see, that's tricky. I wonder whether we can somehow check in LmToProjData if we want to use ListMode or ClistMode. However, to be very honest my first step would have been exactly what Richard did.

**Comment by rijobro** [comment]
Small problem that if you build on a new branch of STIR, `ListModeData.h` will be installed. If you then switch to an older branch, the file will still be in the install location if the user doesn't delete it themselves. This means the CMake `exist` will return true for old versions of STIR. Seems like a small problem though, not that many people will be switching between new and old branches. If they do, the just need to remember to delete the file.
