### ISSUE TITLE
MRAcquisitionData::new_acquisitions_container() returns empty container

### ISSUE THREAD

**Issue by johannesmayer** [CCPPETMR/SIRF#576]
@evgueni-ovtchinnikov @rijobro 
I am having a little trouble getting the `MRAcquisitionmodel::fwd(GadgetronImageData& ic)` method to run with my new kspace sorting.

When the `MRAcquisitionModel` tries to forward project only an image then it will automatically use the template acquisition data as destination.

However, in the process of setting this up to call 
```
MRAcquisitionModel::fwd(GadgetronImageData& ic, CoilSensitivitiesContainer& cc, MRAcquisitionData& ac)
```
a shared pointer to the template acquisition data is created using the two methods 		
```
virtual gadgetron::unique_ptr<MRAcquisitionData> new_acquisitions_container() = 0;
virtual MRAcquisitionData* same_acquisitions_container(const AcquisitionsInfo& info) const = 0;
```
But these actually return copies of the `MRAcquisitionData` with the header/`AcquisitionsInfo` filled in but without the actual data, and then later in the `fwd_(...)` method you get the data and then fill the empty `MRAcquisitionsData` with acquisitions from the template data.

Is there any virtue of doing this versus just cloning the member variable including the data and then replacing the data in the acquisitions? Because I would need to do that but wanted to have your opinion.

**Comment by johannesmayer** [comment]
Is it because when you have an `AcquisitionsFile` you cannot pass the data along?

**Comment by evgueni-ovtchinnikov** [comment]
It is possible - but far from easy to overwrite data in HDF5 file. (My `fill` method for in-file acquisitions actually creates a new file.)

**Comment by johannesmayer** [comment]
I figured it out, I can use a clone() method that has been implemented. Cheers
