### ISSUE TITLE
MR_TESTS_PYTHON coupled to Gadgetrons numerical output

### ISSUE THREAD

**Issue by johannesmayer** [CCPPETMR/SIRF#583]
Hello @rijobro, @evgueni-ovtchinnikov,

I made some progress on the end of getting the MR recon into better shape,
and I got the MR_TESTS_PYTHON to run without them failing because of my code.

I had to set the `storage_scheme` to memory though, because `set_acquisition` is unavailable for class `AcquisitionsDataFile`.

Now the mr python tests fail because we numerically compare Gadgetron recons with our backward model.
I.e. the test asks for a numerical comparison, schematically what is shown in the screenshot below [RD = raw data, GT = Gadgetron, green arrow = num. comparison]:
- we compare a GT recon with the result of SIRFs backward method 
- we compare the raw data after composing the GT recon and a SIRF forward method.

![photo5442779026931428623](https://user-images.githubusercontent.com/10499392/76880452-f93ad200-6877-11ea-845c-38351c8e318b.jpg)

But why does this even make sense, we don't know in principle what happens in Gadgetron, how they norm their transformations and everything? Also don't we couple our tests to what Gadgetron does...

Wouldn't a better test be that composing our SIRF backward and forward method will yield an identity transformation and leave Gadgetron out of the picture in the tests, at least for checking our AcquisitionModel quantitatively?

Best 

Johannes

**Comment by rijobro** [comment]
I didn't write the test, but I suppose the thinking was that Gadgetron did things correctly and so if our output matched theirs, we were doing things properly, too. 

I suppose the fact that your comparison fails means that your results are different to SIRF's results prior to your PR, which is worrying. Either it means you're doing something wrong, or old SIRF was doing something wrong. Which is it?

**Comment by johannesmayer** [comment]
I don't know if there is wrong or right

**Comment by evgueni-ovtchinnikov** [comment]
> Now the mr python tests fail because we numerically compare Gadgetron recons with our backward model.

Fail in what sense? Run-time error? Completely different results? Can you show the output?

**Comment by johannesmayer** [comment]
Yes it fails because the numerical comparison between the recons fail. 
Error message is below in the screenshot.

![image](https://user-images.githubusercontent.com/10499392/76962546-b5030c80-691f-11ea-96ef-cbb66a538b7a.png)

I don't know if there even is a right or wrong, because it depends on what Gadgetron does.
 
What we would have to do is (cf. @ckolbPTB) have an analytic phantom of which we know the analytic result of the FFT, i.e. some ellipsis and the corresponding Bessel function.

**Comment by evgueni-ovtchinnikov** [comment]
I would first checked the norms of reconstructed and backprojected images - they might just have different scaling. Have you compared them visually?

**Comment by johannesmayer** [comment]
No I haven't done that yet,  but I tried to scale them with their norm using
```
imgs_diff = bwd_images / bwd_images.norm() - complex_images/complex_images.norm()
```
but this was not accepted by python saying it cannot perform this operation.
I will do a visual comparison next and let you know :)

**Comment by KrisThielemans** [comment]
some thoughts. There are various possible tests:
1. is the SIRF forward working ok
    - this tends to be very hard to test, but one way is to check consistency with something else, e.g. Gadgetron, the console, or an analytic simulation
2. is the SIRF adjoint working ok (i.e. is it truly the adjoint of the forward)
   - easy in theory (tedious in practice)
3. does SIRF recon work ok? Which has many sub-questions, i.e. which recon.
   - best to do via recon of simulated data
4. does Gadgetron work recon ok?
  - we call their gadgets. would be good to know if they do what we think they do
5. is SIRF recon (somewhat) consistent with Gadgetron recon.
   - although not strictly necessary, any user is going to expect this, and it would be confusing if it isn't.
   - it follows from 3 and 4 of course

Ideally, all of these would be different tests. Maybe @evgueni-ovtchinnikov can clarify which of our current  tests do what.

I suppose the existing test tried to test 1 and 4 somehow (but I didn't check carefully).

Some other comments:
> we numerically compare Gadgetron recons with our backward model

It's an MR way of thinking. It'll only work for fully-sampled data with a system model being the FFT. I don't like it, but I guess it's fine, as long as we document clearly. I agree though with @johannesmayer that there could be choices of normalisation factors here that make things fail.

> I suppose the fact that your comparison fails means that your results are different to SIRF's results prior to your PR, which is worrying. Either it means you're doing something wrong, or old SIRF was doing something wrong. Which is it?

I agree with @rijobro. If a previously working test now fails, it's worrying .

I also agree that it's impossible to diagnose what went on by checking the final number. (An automated test is not the same as a diagnostic test).

**Comment by evgueni-ovtchinnikov** [comment]
@johannesmayer 
```
imgs_diff = bwd_images / bwd_images.norm() - complex_images/complex_images.norm()
```
> ...was not accepted by python saying it cannot perform this operation.

This is weird - division by a scalar is defined for any images (in fact, any SIRF data containers except coil data containers), see e.g. `examples/Python/MR/acquisition_model.py`, line 150. What error message did you get?

**Comment by johannesmayer** [comment]
> I agree with @rijobro. If a previously working test now fails, it's worrying .

That's true, I just figured out something that is not going right, and I sent a request for help to the mailing list. When it is fixed I will review the test again.

**Comment by johannesmayer** [comment]
Ok I found my error, the code is good now, I had implemented averaging out phase encoding points that had been acquired multiple times for cartesian acquisitions and mis-counted somewhere in the code.

Who'da thunk that the only 3 lines of code I added would have made the differenec :(
