### ISSUE TITLE
CIL compatibility

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#589]
For functions in which the output is one of the arguments, the norm in SIRF, as with STIR, is to put the output arguments first. i.e.: `out = do_something(in)` could be `do_something(out, in)`, but shouldn't be `do_something(in, out)`.

I therefore use the following logic in python:
```
def forward(self, im1, im2=None):
    # If im2 is present, im1=output, im2=input
    if im2:
        output=im1
        input=im2
    else:
        input=im1
```

This is at odds with CIL, in which the `CompositionOperator` (which will call our methods) expects this signature `forward(self, x, out=None)`.

As it stands, I therefore can't currently use the `CompositionOperator` with `NiftyResample`.
How can we make the two work with each other? Seems they can't both exist? @paskino @KrisThielemans

**Comment by KrisThielemans** [comment]
I think `out` is often used in Python for this stuff (to avoid reallocation). However, it's a named parameter, not a positional one. I guess that should allow us to resolve this (but don't ask me how!)

**Comment by rijobro** [comment]
In that case it would have to be `forward(self, in, out=None)`. We would no longer be able to call `forward(out_var, in_var)`, but would have to explicitly call `forward(out=out_var, in=in_var)` if we wanted to keep with normal functionality in STIR and elsewhere in SIRF.

**Comment by rijobro** [comment]
And the switch would break backwards compatibility.
