### ISSUE TITLE
SIRF should use std::shared_ptr

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#59]
we're using `boost::shared_ptr` but as we force C++-11, there is no good reason to do that anymore.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov could you create a PR for this based on your `sirf_sptr` branch? Easier to review it then. I guess this supersedes Casper's #61, so close that one (without merging) by referring to your new PR.

**Comment by evgueni-ovtchinnikov** [comment]
Done.
