### ISSUE TITLE
Calling simulated_data=acq_model.forward(image,0,1) without seting it up segfaults (instead of SIRF error)

### ISSUE THREAD

**Issue by AnderBiguri** [CCPPETMR/SIRF#590]
For both 

```
acq_model = pet.AcquisitionModelUsingRayTracingMatrix()
acq_model = pet.AcquisitionModelUsingNiftyPET()
```

if you do `simulated_data=acq_model.forward(image, 0, 1)` without having called `acq_model.set_up(acq_template, image)`, it will _sometimes_ cause a segfault. It is likely that we want a SIRF error here instead.

Based on `SIRF/examples/Python/PET/acquisition_model.py`:

1. If I comment out line 144: `acq_model.set_up(acq_template, image)` I get a proper SIRF error complaining about a lack of `set_up`

2. If I additional comment out Line 146 and uncomment line 147, I get a segfault.

**Comment by rijobro** [comment]
Looking at STIR.py.in, line 146 goes through this:
https://github.com/CCPPETMR/SIRF/blob/36c3d58dd283dd4bbfa1ca83d9f8b29a94c4a0ff/src/xSTIR/pSTIR/STIR.py.in#L1216-L1217

whereas line 147 goes through this logic:
https://github.com/CCPPETMR/SIRF/blob/36c3d58dd283dd4bbfa1ca83d9f8b29a94c4a0ff/src/xSTIR/pSTIR/STIR.py.in#L1210-L1214


On the C++ level, line 147 causes this code to be run:
https://github.com/CCPPETMR/SIRF/blob/36c3d58dd283dd4bbfa1ca83d9f8b29a94c4a0ff/src/xSTIR/cSTIR/stir_x.cpp#L592-L593

And I would guess that it's in these two lines of code that is causing the segfault, as `sptr_ad` is probably a nullptr.

@evgueni-ovtchinnikov

**Comment by KrisThielemans** [comment]
or even `sptr_acq_template_`

**Comment by evgueni-ovtchinnikov** [comment]
Just checked: it is because `sptr_acq_template_` is not set. Need to throw.
