### ISSUE TITLE
matlab kludge to have engine-independent scripts

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/SIRF#6]
Migrated from email thread:

On 8 March 2​​017 at 17:02, Casper da Costa-Luis <imaging@caspersci.uk.to> wrote:
> Haven't tested this, but something like:
>
>     if ispc
>       res = system('mklink /D link targ')
>       if ~res, copyfile('targ', 'link'); end
>     else
>       res = system('ln -sf targ link')
>       if ~res, copyfile('targ', 'link'); end 
>     end
>
> Regards,
> Casper

On 7 March 2017 at 11:01, <evgueni.ovtchinnikov@stfc.ac.uk> wrote:
> How do I update a symbolic link from Matlab?

From: Casper da Costa-Luis [mailto:imaging@caspersci.uk.to]
Sent: 07 March 2017 10:57
To: Ovtchinnikov, Evgueni (STFC,RAL,SC)
Cc: CCP-PETMR-DEVEL@JISCMAIL.AC.UK
Subject: Re: matlab kludge to have engine-independent scripts
> Nice idea. We could try to update a symbolic link and if it fails due to insufficient permissions then do the copy.

On 7 March 2017 at 10:44, Evgueni Ovtchinnikov <evgueni.ovtchinnikov@stfc.ac.uk> wrote:
> A (rather ugly) solution to Matlab’s problem with the absence of ‘import as’, which precludes engine-independent scripts, is to copy the engine package folder to folder +MR/+PET in respective engine selection script.
>
> For example, select_gadgetron.m could copy +mGadgetron (in build/install/matlab) to +MR, and engine-independent scripts should either have ‘import MR.*’ after ‘set_up_mr’ or use MR prefix explicitly.
>
> Slightly less ugly solution would be making a symbolic link, but that unfortunately requires administrator privileges on Windows.
>
> Would this do?

**Comment by KrisThielemans** [comment]
we have decided to avoid symbolic links and copying files as it can run into trouble with permissions etc. A work-around using eval(setup_PET()) has been implemented instead.
