### ISSUE TITLE
SIRF fails to compile STIR master because of std::shared_ptr

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#60]
STIR now switched to using `std::shared_ptr` if compiling with C++-11. This (sadly) creates a confict with `boost::shared_ptr`.
```
/home/travis/build/CCPPETMR/SIRF-SuperBuild/SIRF/src/xSTIR/cSTIR/stir_data_containers.h: In member function boost::shared_ptr<stir::ExamInfo> PETAcquisitionData::get_exam_info_sptr() const:
/home/travis/build/CCPPETMR/SIRF-SuperBuild/SIRF/src/xSTIR/cSTIR/stir_data_containers.h:245:36:error: could not convert stir::ExamData::get_exam_info_sptr() fromstd::shared_ptr<stir::ExamInfo> to boost::shared_ptr<stir::ExamInfo>
   return data()->get_exam_info_sptr();
```
I think ideally we need to use `stir::shared_ptr` for objects returned by STIR functions (e.g. `ProjData::read_from_file` or `get*_sptr()`. That might still be difficult as presumably we're storing this sometimes as `boost::shared_ptr`?

Alternatively, we could force STIR to compile with C++-11 in the superbuild. That's not so nice though as it prevents using older versions of STIR.

See also #59

**Comment by KrisThielemans** [comment]
See [this answer](https://stackoverflow.com/questions/6326757/conversion-from-boostshared-ptr-to-stdshared-ptr/12605002#12605002) for a way to convert ([apparently dangerous](https://stackoverflow.com/questions/12314967/cohabitation-of-boostshared-ptr-and-stdshared-ptr) when using `std::weak_ptr` but we're not).

**Comment by KrisThielemans** [comment]
This is temporarily fixed in the https://github.com/CCPPETMR/SIRF-SuperBuild/commit/7478a648184844c65a964dfbab7cc617caff8028 by compiling STIR with `-DSTIR_USE_BOOST_SHARED_PTR`

**Comment by evgueni-ovtchinnikov** [comment]
xSTIR now uses stir::shared_ptr and xGadgetron uses std::shared_ptr.
