### ISSUE TITLE
cope with STIR shared_ptr<const DiscretisedDensity> etc

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#613]
https://github.com/UCL/STIR/pull/481 will break backwards compatibility. Not sure if SIRF needs changes, but if so, ideally we do them such that both previous and new STIR will compile (as in #607)

**Comment by KrisThielemans** [comment]
@rijobro this is ready to merge. I'll do the `exam_info` one as a separate PR, as it's quite involved.

Did you check if SIRF needs any changes to cope with this STIR version? If so, best to have those ready (or if backwards compatible, merged first)

**Comment by rijobro** [comment]
```
auto sptr_im = prior.get_anatomical_image_sptr();
shared_ptr<STIRImageData> sptr_id(new STIRImageData(sptr_im));
return newObjectHandle(sptr_id);
```
Constructor of STIRImageData doesn't take a const DiscDensity as it needs to be able to modify the data if desired. This means lots of copying of data, but unavoidable I think.
