### ISSUE TITLE
Need code-style and conventions specification

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#72]
We have some info on conventions in the User's Guide, but nothing in the Developer's Guide. In particular, no C++ conventions. These need to be added, I suggest starting from the relevant things in the STIR Developer's guide. I think the Developer's Guide is the correct place for this.

example things to add:
- naming of files/classes/functions
- error handling (i.e. throw exceptions)
- white space handling (to be added later)

**Comment by casperdcl** [comment]
pick something which `clang-format` can (mostly) automatically handle?

**Comment by evgueni-ovtchinnikov** [comment]
added by rijobro
