### ISSUE TITLE
running MATLAB from ctest

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#73]
Further the email conversation from @evgueni-ovtchinnikov .
> I managed to run Matlab tests via ctest on Windows (works even directly from Visual Studio now). No
> luck on UCL Linux yet, as Matlab does not recognize option –sd that defines Matlab starting folder. I
> could not find any other way to let Matlab know where the test script test_all.m is.
>
>Giving the full path, i.e.
>
>  matlab –nodesktop –r C:/…/test_all
>
>does not work (Matlab needs the function test_all, not the file test_all.m).
>
>Just checked: it appears, -sd is only available since 2017a.

I’ve investigated this a bit. I think we need 2 things:

# Specify the location of the tests in the CMake file

`WORKING_DIRECTORY` should do it.
```cmake
add_test(NAME <name> COMMAND <command> [<arg>...]
         [CONFIGURATIONS <config>...]
         [WORKING_DIRECTORY <dir>])
```
# Run the test in MATLAB

The tricky bit is to convince matlab to run things and always exit, even if there’s a failure. 
That’s surprisingly difficult as normally the matlab prompt “stays alive” when there was an error in the script. I’ve played around with this for SWIG and came up with the following
```sh
matlab -nosplash -nodesktop -nojvm -r "ver; try; test_all; catch err, fprintf(2,['ERROR: ' err.message '\n']),exit(1), end, exit(0)"
```
That seems to work almost ok. Main problems

## Getting the output
(at least on Windows) the MATLAB output is never shown on stdout, so will not appear in `LastTest.log` etc, and is therefore not possible to know what went wrong. We can tell matlab to redirect output via the `-logfile` argument, but then the user needs to know where that logfile will be. I think this should be our short-term solution though, just document it.

Some extra pointers
- ctest doesn't use a shell to launch the test, so you cannot run multiple commands. [more info](https://stackoverflow.com/questions/36304289/how-to-use-redirection-in-cmake-add-test) including some horrible workarounds to create batch/shell scripts to do the trick.
- [various work-arounds to get matlab to write to stdout](https://uk.mathworks.com/matlabcentral/answers/91607-how-can-i-redirect-the-command-window-output-to-stdout-and-stderr-when-running-matlab-7-8-r2009a-i), including undocumented options '-log -wait' which do the trick (and still work on my Windows matlab.

## disabling the user's `startup.m`
If there are errors in the user's `startup`, we'll never get to our tests. We'll also get them in our output. Moreover, the user's `startup` might slow this down. There doesn't seem to be a documented way to prevent running the user's `startup.m`, aside from creating one in the current folder. In any case, a user might need to know of conflicts between their `startup.m` and SIRF, so I think we should ignore this problem.

If you disagree, we could create an empty `startup.m`, or put `ver` in there, or indeed put the content of `test_all.m` in `startup.m` but this latter solution leads to somewhat confusing output when the test fails. An example in my system (where I haven't set-up `MATLABPATH` correctly yet)
```

For online documentation, see http://www.mathworks.com/support
For product information, visit www.mathworks.com.

Running test1.m
Warning: Executing startup failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should be resolved as soon as possible.  Error
detected was:
MATLAB:UndefinedFunction
Undefined function 'set_up_PET' for input arguments of type 'double'.
```

**Comment by KrisThielemans** [comment]
by the way, need to use `${Matlab_MAIN_PROGRAM}$, not just `matlab`

**Comment by evgueni-ovtchinnikov** [comment]
WORKING_DIRECTORY should do it.

add_test(NAME <name> COMMAND <command> [<arg>...]
         [CONFIGURATIONS <config>...]
         [WORKING_DIRECTORY <dir>])

But it does not, which is why I tried -sd.

**Comment by evgueni-ovtchinnikov** [comment]
by the way, need to use ${Matlab_MAIN_PROGRAM}, not just matlab


message("matlab: ${Matlab_MAIN_PROGRAM}")

prints

matlab:

**Comment by evgueni-ovtchinnikov** [comment]
matlab -nosplash -nodesktop -nojvm -r "ver; try; test_all; catch err, fprintf(2,['ERROR: ' err.message '\n']),exit(1), end, exit(0)"

produces error message:

ver; try; test_all; catch err, fprintf(2,['ERROR: ' err.message '
                                                                 |
Error: Character vector is not terminated properly.

**Comment by evgueni-ovtchinnikov** [comment]
found the bug: I was trying to run run_all instead of test_all

now have seg fault on Linux, apparently because of the matlab problems with the compiler

some progress though!

**Comment by KrisThielemans** [comment]
Turns out that CMake's [FindMatlab](https://cmake.org/cmake/help/latest/module/FindMatlab.html) provides a macro for this: `matlab_add_unit_test`. It dseems to resolve the problems I mentioned above. I've used this in 6dae9c4b9bc6802d98a60a409e6ea48938ae306d and it works on my Windows 10 with Matlab 2016b.

It might need an `exit(0)` statement at the end of `test_all.m` on Linux (according to the doc), but I didn't need it on Windows.

**Comment by evgueni-ovtchinnikov** [comment]
matlab_add_unit_test works fine on Windows, but on Linux (UCL) I get:

4:     identifier: 'MATLAB:UndefinedFunction'
4:        message: 'Undefined function or variable 'test_all'.'
4:          cause: {}
4:          stack: [0x1 struct]

**Comment by KrisThielemans** [comment]
ah. seems the MATLAB path doesn't contain the current directory then on Linux? Or the current working directory is incorrect?  I guess you can investigate by using `UNITTEST_PRECOMMAND` to type the working directory `pwd` and the path. Possibly the CMake on the UCL-system is too old (let's hope so).

**Comment by evgueni-ovtchinnikov** [comment]
it turned out matlab_add_unit_test needs ADDITIONAL_PATH instead of WORKING_DIRECTORY

now Matlab tests work under Linux too

**Comment by KrisThielemans** [comment]
@rijobro  to check on Mac

**Comment by evgueni-ovtchinnikov** [comment]
According to Richard, all tests are now working on OSX.
