### ISSUE TITLE
create documentation seperate folder

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#74]
- [ ] move `UserGuide.md` to `documentation/UsersGuide.md` etc
- [ ] add UserSpec to `documentation/`

**Comment by KrisThielemans** [comment]
Can use [pandoc](https://github.com/jgm/pandoc/releases/tag/2.0.5) for the conversion of our word files. This seems to work well but might need some manual help of course.
```
pandoc -t gfm -o Software-User-Specification.md CCP-PETMR-Software-User-Specification.docx
```
where 'gfm' is 'GitHub-flavored-markdown`.

To check locally how it displays as how GitHub would do, I use the following:
```
pip install grip
grip Software-User-Specification.md
```
Then just open a browser and go to  http://localhost:6419/

**Comment by evgueni-ovtchinnikov** [comment]
done
