### ISSUE TITLE
PET raw data wiki

### ISSUE THREAD

**Issue by bathomas** [CCPPETMR/SIRF#84]
Write PET wiki page equivalent to https://github.com/CCPPETMR/SIRF/wiki/MR-raw-data.

**Comment by bathomas** [comment]
I have started a page on raw PET data for the mMR [https://github.com/CCPPETMR/SIRF/wiki/PET-raw-data](https://github.com/CCPPETMR/SIRF/wiki/PET-raw-data). Please feel free to comment/improve. If another site has access to the scanner console, and would be willing to confirm my stages for the export procedure, that would be very helpful.

**Comment by bathomas** [comment]
Updated to state that headers converted with `convertSiemensToInterfile.sh` (STIR) are no longer supported.

**Comment by KrisThielemans** [comment]
confirmed by Ashley Gillman, so closing
