### ISSUE TITLE
error in for loop in stir_data_containers.cpp

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#85]
we get the following warning
```C++
Users/travis/build/CCPPETMR/SIRF-SuperBuild/SIRF/src/xSTIR/cSTIR/stir_data_containers.cpp:218:8: warning: inequality comparison result unused [-Wunused-comparison]

                iter != data().end_all(), iter_x != x.data().end_all(); iter++, iter_x++) {
```
This for condition should use an `&&`. However, I guess that both should have the same size so I would add a check after the `for` loop that indeed both iterators are at `end_all`.

Probably the same at L261

**Comment by evgueni-ovtchinnikov** [comment]
corrected
