### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/SIRF#9]
* [x] Provide packages documentation (comments in `pGadgetron.py`, `pStir.py`, `+mGadgetron`, `+mStir`). (Needs PET feedback)
* [x] Write User’s Guide for basic users (those using engine-independent demos only)
* [ ] Update pseudo-code, User Specification and Design Overview documents

**Comment by KrisThielemans** [comment]
Notes added to the current documents refering to the User's Guide for current specification. We will do a more complete update for v1.0.
