### ISSUE TITLE
create file with list of steps to follow to make a release

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#91]
things to do include creating branches (maybe no longer needed), updating `SIRF-Superbuild/version_config.cmake` and any version numbers anywhere (e.g. `SIRF/CMakeLists.txt` but presumably also documentation), any references to specific commits/branches (`update_VM.sh`?). 
Then VM creation etc. testing...

At the very end git tag and push with tags. 

where do we put this file with instructions?

**Comment by KrisThielemans** [comment]
- no branch needed.
- add update `CHANGES.md`
- create docker images
- run doxygen

create `doc/ReleaseChecklist.md`

**Comment by KrisThielemans** [comment]
See PR #93

**Comment by casperdcl** [comment]
thanks to https://github.com/CCPPETMR/SIRF-SuperBuild/pull/86 can replace:

- ~~create~~ -> tag docker images
