### ISSUE TITLE
show_2D_array etc should not rescale image

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/SIRF#94]
It looks like the scale of the image in `show_2D_array` is always set to `[0 255]` or something. This should not be done, definitely not for PET. I cannot see a good reason for it?

**Comment by evgueni-ovtchinnikov** [comment]
sorry, do not understand, show_2D_array does not set anything:

    plt.figure()
    plt.title(title)
    plt.imshow(array)
    if colorbar:
        plt.colorbar()
    fignums = plt.get_fignums()
    print('Close Figure %d window to continue...' % fignums[-1])
    plt.show()

**Comment by KrisThielemans** [comment]
we used the matlab demo to show the attenuation image, and the colorbar was 0..255 or so. It's ok in Python

**Comment by evgueni-ovtchinnikov** [comment]
still do not get you

we have an array with an arbitrary range of positive values

to plot it we do

    scale = max(abs(array(:)))/255;           % abs is actually extra, sorry
    image = uint8(array(:,:,index(z))/scale); % map array values onto [0, 255] range for plotting
    imshow(image, 'Colormap', jet(255))       % plot

what is wrong with this for PET data?

**Comment by KrisThielemans** [comment]
PET data is supposed to be quantitative (if everything's done well), so the numbers have an absolute scale. best to show the original scale in the colourbar.

By the way, images could contain negative values as well (cannot assume it's [0..max])

**Comment by evgueni-ovtchinnikov** [comment]
still not sure I understand - do you mean there should be some one-for-all-images value instead of max(abs(array(:)))?

not difficult to modify for negative values, but will this ever be needed? can wait until 1.1 anyway

**Comment by KrisThielemans** [comment]
There should be no reason for the rescaling. The following should do
```matlab
cmax = max(array(:));
cmin = min(array(:));
imshow(image, [cmin,cmax],'Colormap', jet(255)) 
```
(I haven't tried)

**Comment by evgueni-ovtchinnikov** [comment]
fixed on devel
